const wordsAndHints = [
    { word: "Apfel", hints: ["Frucht", "Rot", "Baum", "Obst", "Kerngehäuse"] },
    { word: "Hund", hints: ["Tier", "Bellt", "Haustier", "Loyal", "Vierbeiner"] },
    { word: "Buch", hints: ["Lesen", "Seiten", "Geschichte", "Wissen", "Autor"] },
    { word: "Auto", hints: ["Fahren", "Räder", "Motor", "Verkehr", "Transport"] },
    { word: "Haus", hints: ["Wohnen", "Dach", "Zuhause", "Gebäude", "Fenster"] },
    { word: "Blume", hints: ["Pflanze", "Blüte", "Garten", "Duft", "Farbe"] },
    { word: "Sonne", hints: ["Himmel", "Warm", "Licht", "Tag", "Strahl"] },
    { word: "Wasser", hints: ["Trinken", "Flüssig", "Meer", "Nass", "Durst"] },
    { word: "Baum", hints: ["Wald", "Grün", "Holz", "Wurzel", "Ast"] },
    { word: "Stuhl", hints: ["Sitzen", "Möbel", "Bein", "Rückenlehne", "Sitzfläche"] },
    { word: "Tisch", hints: ["Essen", "Platte", "Vierbeinig", "Möbel", "Arbeitsfläche"] },
    { word: "Schule", hints: ["Lernen", "Lehrer", "Klasse", "Unterricht", "Pausenhof"] },
    { word: "Computer", hints: ["Technik", "Bildschirm", "Tastatur", "Maus", "Internet"] },
    { word: "Telefon", hints: ["Anrufen", "Sprechen", "Handy", "Kommunikation", "Nummer"] },
    { word: "Uhr", hints: ["Zeit", "Zeiger", "Tickt", "Armband", "Wecker"] },
    { word: "Geld", hints: ["Kaufen", "Zahlen", "Münzen", "Scheine", "Reichtum"] },
    { word: "Stadt", hints: ["Gebäude", "Straßen", "Menschen", "Zentrum", "Groß"] },
    { word: "Fluss", hints: ["Wasser", "Strömung", "Brücke", "Ufer", "Schiff"] },
    { word: "Berg", hints: ["Hoch", "Wandern", "Gipfel", "Natur", "Aussicht"] },
    { word: "Wolke", hints: ["Himmel", "Regen", "Weiß", "Form", "Schwimmt"] },
    { word: "Vogel", hints: ["Fliegen", "Feder", "Nest", "Zwitschern", "Flügel"] },
    { word: "Fisch", hints: ["Schwimmen", "Wasser", "Schuppen", "Flosse", "Angeln"] },
    { word: "Brot", hints: ["Essen", "Backen", "Teig", "Bäcker", "Scheibe"] },
    { word: "Käse", hints: ["Milch", "Gelb", "Loch", "Würzig", "Brotzeit"] },
    { word: "Milch", hints: ["Trinken", "Weiß", "Kuh", "Kalzium", "Frühstück"] },
    { word: "Ei", hints: ["Huhn", "Frühstück", "Oval", "Spiegelei", "Backen"] },
    { word: "Salz", hints: ["Würzen", "Weiß", "Kristall", "Meer", "Geschmack"] },
    { word: "Zucker", hints: ["Süß", "Weiß", "Kristall", "Kaffee", "Süßigkeiten"] },
    { word: "Kaffee", hints: ["Trinken", "Schwarz", "Bohne", "Wachmacher", "Heiß"] },
    { word: "Tee", hints: ["Trinken", "Heiß", "Beutel", "Kräuter", "Tasse"] },
    { word: "Hemd", hints: ["Kleidung", "Ärmel", "Knopf", "Kragen", "Stoff"] },
    { word: "Hose", hints: ["Kleidung", "Bein", "Bund", "Jeans", "Gürtel"] },
    { word: "Schuh", hints: ["Fuß", "Laufen", "Sohle", "Schnürsenkel", "Paar"] },
    { word: "Hut", hints: ["Kopf", "Tragen", "Krempe", "Schutz", "Mode"] },
    { word: "Regen", hints: ["Nass", "Tropfen", "Schirm", "Wolken", "Pfütze"] },
    { word: "Schnee", hints: ["Kalt", "Weiß", "Flocke", "Winter", "Schneeball"] },
    { word: "Wind", hints: ["Luft", "Bläst", "Sturm", "Bewegung", "Kalt"] },
    { word: "Feuer", hints: ["Heiß", "Flamme", "Rauch", "Brennen", "Lagerfeuer"] },
    { word: "Erde", hints: ["Planet", "Grün", "Boden", "Garten", "Land"] },
    { word: "Mond", hints: ["Nacht", "Himmel", "Sichel", "Leuchtet", "Satelit"] },
    { word: "Stern", hints: ["Nacht", "Funkelt", "Weit", "Himmel", "Leuchtet"] },
    { word: "Straße", hints: ["Fahren", "Asphalt", "Weg", "Verkehr", "Schild"] },
    { word: "Brücke", hints: ["Fluss", "Überqueren", "Bauwerk", "Verbindung", "Höhe"] },
    { word: "Tür", hints: ["Öffnen", "Schließen", "Eingang", "Raum", "Klinke"] },
    { word: "Fenster", hints: ["Glas", "Blick", "Rahmen", "Licht", "Öffnen"] },
    { word: "Bett", hints: ["Schlafen", "Matratze", "Kissen", "Decke", "Nacht"] },
    { word: "Küche", hints: ["Kochen", "Herd", "Essen", "Raum", "Pfanne"] },
    { word: "Bad", hints: ["Duschen", "Toilette", "Sauber", "Wasser", "Waschbecken"] },
    { word: "Garten", hints: ["Pflanzen", "Blumen", "Grün", "Erde", "Gemüse"] },
    { word: "Park", hints: ["Grün", "Bäume", "Spazieren", "Bank", "Erholung"] },
    { word: "Ball", hints: ["Spielen", "Rund", "Werfen", "Sport", "Springt"] },
    { word: "Bleistift", hints: ["Schreiben", "Spitze", "Holz", "Zeichnen", "Radiergummi"] },
    { word: "Schere", hints: ["Schneiden", "Blatt", "Spitz", "Basteln", "Griff"] },
    { word: "Hammer", hints: ["Nagel", "Schlagen", "Werkzeug", "Holz", "Griff"] },
    { word: "Schlüssel", hints: ["Öffnen", "Tür", "Metall", "Schloss", "Bund"] },
    { word: "Spiegel", hints: ["Reflektiert", "Bild", "Glas", "Anschauen", "Wand"] },
    { word: "Decke", hints: ["Wärmt", "Schlafen", "Stoff", "Bett", "Kuschelig"] },
    { word: "Kissen", hints: ["Kopf", "Weich", "Schlafen", "Sofa", "Bezug"] },
    { word: "Seife", hints: ["Waschen", "Schaum", "Sauber", "Hände", "Duft"] },
    { word: "Zahnbürste", hints: ["Zähne", "Putzen", "Mund", "Hygiene", "Borsten"] },
    { word: "Handtuch", hints: ["Trocknen", "Nass", "Baumwolle", "Dusche", "Bad"] },
    { word: "Tasche", hints: ["Tragen", "Inhalt", "Stoff", "Geld", "Schulter"] },
    { word: "Rucksack", hints: ["Tragen", "Schule", "Wandern", "Gepäck", "Schultergurte"] },
    { word: "Brille", hints: ["Sehen", "Augen", "Linse", "Gestell", "Nase"] },
    { word: "Mütze", hints: ["Kopf", "Wärmt", "Strick", "Winter", "Mode"] },
    { word: "Schal", hints: ["Hals", "Wärmt", "Stoff", "Winter", "Knoten"] },
    { word: "Handschuh", hints: ["Hände", "Wärmt", "Finger", "Winter", "Paar"] },
    { word: "Socke", hints: ["Fuß", "Wärmt", "Stoff", "Schuh", "Paar"] },
    { word: "Gürtel", hints: ["Hose", "Hält", "Leder", "Schnalle", "Taille"] },
    { word: "Kleid", hints: ["Frau", "Stoff", "Anziehen", "Fest", "Sommer"] },
    { word: "Rock", hints: ["Frau", "Stoff", "Taille", "Kurz", "Lang"] },
    { word: "Pullover", hints: ["Wärmt", "Stoff", "Ärmel", "Winter", "Strick"] },
    { word: "Jacke", hints: ["Wärmt", "Stoff", "Reißverschluss", "Außen", "Regen"] },
    { word: "Mantel", hints: ["Lang", "Wärmt", "Stoff", "Winter", "Knöpfe"] },
    { word: "Halskette", hints: ["Hals", "Schmuck", "Kette", "Anhänger", "Glänzt"] },
    { word: "Ring", hints: ["Finger", "Schmuck", "Metall", "Glänzt", "Hochzeit"] },
    { word: "Ohrring", hints: ["Ohr", "Schmuck", "Hängt", "Glänzt", "Paar"] },
    { word: "Armband", hints: ["Arm", "Schmuck", "Kette", "Glänzt", "Uhr"] },
    { word: "Umschlag", hints: ["Brief", "Papier", "Post", "Empfänger", "Zukleben"] },
    { word: "Briefmarke", hints: ["Umschlag", "Post", "Klebt", "Wert", "Bild"] },
    { word: "Stift", hints: ["Schreiben", "Tinte", "Papier", "Kappe", "Farbe"] },
    { word: "Hefter", hints: ["Papier", "Klammer", "Büro", "Dokumente", "Sammelt"] },
    { word: "Locher", hints: ["Papier", "Loch", "Büro", "Ordner", "Stanzt"] },
    { word: "Schreibtisch", hints: ["Arbeiten", "Büro", "Stuhl", "Oberfläche", "Schublade"] },
    { word: "Lampe", hints: ["Licht", "Dunkel", "Leuchtet", "Stecker", "Birne"] },
    { word: "Kerze", hints: ["Licht", "Flamme", "Wachs", "Duft", "Romantisch"] },
    { word: "Streichelt", hints: ["Feuer", "Anzünden", "Holz", "Reibt", "Funke"] },
    { word: "Seil", hints: ["Bindet", "Knoten", "Stark", "Klettern", "Lang"] },
    { word: "Korb", hints: ["Tragen", "Füllen", "Geflecht", "Einkaufen", "Picknick"] },
    { word: "Eimer", hints: ["Wasser", "Tragen", "Füllen", "Reinigen", "Henkel"] },
    { word: "Besen", hints: ["Kehren", "Sauber", "Boden", "Stiel", "Borsten"] },
    { word: "Schaufel", hints: ["Graben", "Erde", "Sand", "Garten", "Stiel"] },
    { word: "Gießkanne", hints: ["Pflanzen", "Wasser", "Gießen", "Garten", "Tülle"] },
    { word: "Topf", hints: ["Kochen", "Essen", "Herd", "Deckel", "Griff"] },
    { word: "Pfanne", hints: ["Braten", "Essen", "Herd", "Griff", "Flach"] },
    { word: "Teller", hints: ["Essen", "Geschirr", "Rund", "Porzellan", "Spülen"] },
    { word: "Tasse", hints: ["Trinken", "Kaffee", "Tee", "Henkel", "Heiß"] },
    { word: "Glas", hints: ["Trinken", "Flüssig", "Durchsichtig", "Zerbrechlich", "Wasser"] },
    { word: "Besteck", hints: ["Essen", "Gabel", "Messer", "Löffel", "Metall"] },
    { word: "Löffel", hints: ["Essen", "Suppe", "Mund", "Besteck", "Rund"] },
    { word: "Messer", hints: ["Schneiden", "Scharf", "Besteck", "Küche", "Griff"] },
    { word: "Gabel", hints: ["Essen", "Spitzt", "Besteck", "Zinken", "Küche"] },
    { word: "Herd", hints: ["Kochen", "Warm", "Küche", "Backofen", "Platte"] },
    { word: "Kühlschrank", hints: ["Kühlt", "Essen", "Getränke", "Küche", "Türe"] },
    { word: "Mikrowelle", hints: ["Wärmt", "Essen", "Schnell", "Küche", "Knöpfe"] },
    { word: "Toaster", hints: ["Brot", "Röstet", "Frühstück", "Warm", "Knusprig"] },
    { word: "Spülmaschine", hints: ["Reinigt", "Geschirr", "Küche", "Wasser", "Sauber"] },
    { word: "Waschmaschine", hints: ["Wäscht", "Kleidung", "Sauber", "Wasser", "Trommel"] },
    { word: "Trockner", hints: ["Trocknet", "Kleidung", "Warm", "Wäsche", "Luft"] },
    { word: "Staubsauger", hints: ["Saugt", "Dreck", "Reinigt", "Boden", "Schlauch"] },
    { word: "Bügelbrett", hints: ["Bügeln", "Kleidung", "Glatt", "Dampf", "Klappt"] },
    { word: "Bügeleisen", hints: ["Bügelt", "Kleidung", "Heiß", "Dampf", "Glatt"] },
    { word: "Eimer", hints: ["Wasser", "Tragen", "Putz", "Reinigt", "Henkel"] },
    { word: "Wischmop", hints: ["Wischen", "Boden", "Nass", "Reinigt", "Stiel"] },
    { word: "Schrubber", hints: ["Bürstet", "Boden", "Hartnäckig", "Reinigt", "Stiel"] },
    { word: "Mülleimer", hints: ["Abfall", "Entsorgen", "Geruch", "Deckel", "Leert"] },
    { word: "Besen", hints: ["Fegen", "Dreck", "Boden", "Stiel", "Borsten"] },
    { word: "Ofen", hints: ["Backen", "Heiß", "Küche", "Pizza", "Blech"] },
    { word: "Lichtschalter", hints: ["Licht", "An", "Aus", "Wand", "Klick"] },
    { word: "Steckdose", hints: ["Strom", "Stecker", "Wand", "Gerät", "Elektrizität"] },
    { word: "Glühbirne", hints: ["Leuchtet", "Licht", "Strom", "Glas", "Fassung"] },
    { word: "Batterie", hints: ["Strom", "Gerät", "Energie", "Aufladen", "Klein"] },
    { word: "Kabel", hints: ["Verbindet", "Strom", "Daten", "Lang", "Flexibel"] },
    { word: "Drucker", hints: ["Druckt", "Papier", "Tinte", "Büro", "Computer"] },
    { word: "Scanner", hints: ["Scannt", "Bild", "Dokument", "Computer", "Digitalisiert"] },
    { word: "Tastatur", hints: ["Computer", "Tippen", "Buchstaben", "Tasten", "Eingabe"] },
    { word: "Maus", hints: ["Computer", "Zeiger", "Klicken", "Bewegt", "Kabel"] },
    { word: "Monitor", hints: ["Computer", "Bildschirm", "Anzeige", "Sehen", "Flach"] },
    { word: "Lautsprecher", hints: ["Ton", "Musik", "Sprache", "Hören", "Box"] },
    { word: "Kopfhörer", hints: ["Hören", "Musik", "Ohr", "Kabel", "Still"] },
    { word: "Mikrofon", hints: ["Sprechen", "Aufnehmen", "Ton", "Stimme", "Hören"] },
    { word: "Kamera", hints: ["Foto", "Film", "Bild", "Objektiv", "Aufnehmen"] },
    { word: "Fernbedienung", hints: ["TV", "Schaltet", "Knöpfe", "Gerät", "Batterie"] },
    { word: "Schrank", hints: ["Kleidung", "Türen", "Möbel", "Lagern", "Fächer"] },
    { word: "Regal", hints: ["Bücher", "Fächer", "Möbel", "Lagern", "Wand"] },
    { word: "Sofa", hints: ["Sitzen", "Weich", "Wohnzimmer", "Kissen", "Gemütlich"] },
    { word: "Sessel", hints: ["Sitzen", "Einzeln", "Wohnzimmer", "Armlehne", "Bequem"] },
    { word: "Teppich", hints: ["Boden", "Weich", "Wärmt", "Farbe", "Muster"] },
    { word: "Vorhang", hints: ["Fenster", "Sichtschutz", "Stoff", "Zieht", "Dunkel"] },
    { word: "Bild", hints: ["Wand", "Rahmen", "Kunst", "Foto", "Anschauen"] },
    { word: "Vase", hints: ["Blumen", "Wasser", "Schmuck", "Glas", "Tisch"] },
    { word: "Kamin", hints: ["Feuer", "Wärme", "Holz", "Rauch", "Gemütlich"] },
    { word: "Heizung", hints: ["Wärmt", "Rohre", "Zimmer", "Winter", "Thermostat"] },
    { word: "Thermostat", hints: ["Temperatur", "Regelt", "Heizung", "Raum", "Anzeige"] },
    { word: "Ventilator", hints: ["Kühlt", "Luft", "Bewegt", "Sommer", "Flügel"] },
    { word: "Klimaanlage", hints: ["Kühlt", "Luft", "Raum", "Sommer", "Angenehm"] },
    { word: "Wecker", hints: ["Weckt", "Zeit", "Geräusch", "Morgen", "Klingelt"] },
    { word: "Schlafzimmer", hints: ["Schlafen", "Bett", "Ruhe", "Raum", "Nacht"] },
    { word: "Wohnzimmer", hints: ["Wohnen", "Sofa", "Fernsehen", "Raum", "Gemütlich"] },
    { word: "Esszimmer", hints: ["Essen", "Tisch", "Stühle", "Raum", "Familie"] },
    { word: "Flur", hints: ["Eingang", "Türen", "Gang", "Verbindung", "Garderobe"] },
    { word: "Keller", hints: ["Unten", "Lagern", "Dunkel", "Feucht", "Abstellraum"] },
    { word: "Dachboden", hints: ["Oben", "Lagern", "Staubig", "Spinnen", "Speicher"] },
    { word: "Balkon", hints: ["Draußen", "Aussicht", "Pflanzen", "Sitzen", "Frischluft"] },
    { word: "Terrasse", hints: ["Draußen", "Boden", "Garten", "Sitzen", "Sonne"] },
    { word: "Zaun", hints: ["Grenze", "Holz", "Metall", "Schutz", "Garten"] },
    { word: "Tor", hints: ["Öffnet", "Schließt", "Zaun", "Eingang", "Fahrzeug"] },
    { word: "Briefkasten", hints: ["Post", "Briefe", "Einwurf", "Haus", "Leerung"] },
    { word: "Türklingel", hints: ["Klingelt", "Besucher", "Geräusch", "Tür", "Drücken"] },
    { word: "Garagentor", hints: ["Garage", "Auto", "Öffnet", "Schließt", "Groß"] },
    { word: "Schuppen", hints: ["Garten", "Werkzeug", "Lagern", "Klein", "Holz"] },
    { word: "Gewächshaus", hints: ["Pflanzen", "Glas", "Warm", "Züchten", "Garten"] },
    { word: "Schwimmbad", hints: ["Schwimmen", "Wasser", "Pool", "Sommer", "Nass"] },
    { word: "Grill", hints: ["Fleisch", "Braten", "Feuer", "Sommer", "Rauch"] },
    { word: "Sonnenschirm", hints: ["Sonne", "Schatten", "Strand", "Garten", "Groß"] },
    { word: "Gartenstuhl", hints: ["Garten", "Sitzen", "Draußen", "Klappt", "Wetterfest"] },
    { word: "Gartentisch", hints: ["Garten", "Essen", "Draußen", "Wetterfest", "Rund"] },
    { word: "Schaukel", hints: ["Spielen", "Schwingt", "Garten", "Kind", "Holz"] },
    { word: "Rutsche", hints: ["Spielen", "Runter", "Garten", "Kind", "Schnell"] },
    { word: "Sandkasten", hints: ["Spielen", "Sand", "Garten", "Kind", "Bauen"] },
    { word: "Fahrrad", hints: ["Fahren", "Räder", "Pedale", "Lenker", "Kette"] },
    { word: "Helm", hints: ["Kopf", "Schutz", "Fahrrad", "Hart", "Sicherheit"] },
    { word: "Skateboard", hints: ["Fahren", "Räder", "Brett", "Trick", "Rollschuhe"] },
    { word: "Roller", hints: ["Fahren", "Räder", "Lenker", "Trittbrett", "Kind"] },
    { word: "Inliner", hints: ["Fahren", "Rollen", "Fuß", "Sport", "Schiene"] },
    { word: "Schlittschuh", hints: ["Eis", "Gleiten", "Kufen", "Sport", "Winter"] },
    { word: "Ski", hints: ["Schnee", "Fahren", "Stöcke", "Sport", "Winter"] },
    { word: "Snowboard", hints: ["Schnee", "Fahren", "Brett", "Sport", "Winter"] },
    { word: "Schlitten", hints: ["Schnee", "Rutschen", "Rodeln", "Winter", "Holz"] },
    { word: "Strand", hints: ["Meer", "Sand", "Sonne", "Urlaub", "Baden"] },
    { word: "Welle", hints: ["Meer", "Bewegt", "Wasser", "Brandung", "Surfen"] },
    { word: "Muschel", hints: ["Strand", "Meer", "Leer", "Schale", "Sammelt"] },
    { word: "Seestern", hints: ["Meer", "Tier", "Arme", "Strand", "Fünfzackig"] },
    { word: "Qualle", hints: ["Meer", "Schleimig", "Sting", "Durchsichtig", "Schirm"] },
    { word: "Krabbe", hints: ["Meer", "Tier", "Scheren", "Läuft", "Panzer"] },
    { word: "Robbe", hints: ["Meer", "Tier", "Schwimmt", "Flossen", "Fisch"] },
    { word: "Delphin", hints: ["Meer", "Tier", "Intelligent", "Springt", "Schwimmt"] },
    { word: "Hai", hints: ["Meer", "Tier", "Scharf", "Gefährlich", "Flosse"] },
    { word: "Wal", hints: ["Meer", "Tier", "Groß", "Schwimmt", "Atemloch"] },
    { word: "Boot", hints: ["Wasser", "Fährt", "Segel", "Ruder", "Angeln"] },
    { word: "Schiff", hints: ["Wasser", "Groß", "Fährt", "Transport", "Meer"] },
    { word: "Flugzeug", hints: ["Fliegt", "Himmel", "Reisen", "Flügel", "Pilot"] },
    { word: "Hubschrauber", hints: ["Fliegt", "Rotor", "Himmel", "Schwebt", "Rettung"] },
    { word: "Rakete", hints: ["Fliegt", "Weltall", "Start", "Schnell", "Stern"] },
    { word: "Zug", hints: ["Fährt", "Schiene", "Wagen", "Reisen", "Lokomotive"] },
    { word: "Bus", hints: ["Fährt", "Straße", "Öffentlich", "Hält", "Passagiere"] },
    { word: "Taxi", hints: ["Fährt", "Mieten", "Bezahlt", "Transport", "Gelb"] },
    { word: "Fähre", hints: ["Wasser", "Transport", "Fährt", "Auto", "Passagiere"] },
    { word: "U-Bahn", hints: ["Untergrund", "Fährt", "Stadt", "Schiene", "Station"] },
    { word: "Straßenbahn", hints: ["Schiene", "Fährt", "Stadt", "Öffentlich", "Hält"] },
    { word: "Ampel", hints: ["Licht", "Rot", "Grün", "Gelb", "Verkehr"] },
    { word: "Verkehrsschild", hints: ["Zeichen", "Straße", "Regel", "Information", "Fahren"] },
    { word: "Polizei", hints: ["Schützt", "Gesetz", "Uniform", "Auto", "Sicherheit"] },
    { word: "Feuerwehr", hints: ["Löscht", "Feuer", "Uniform", "Schlauch", "Helden"] },
    { word: "Krankenhaus", hints: ["Heilt", "Krank", "Arzt", "Pfleger", "Medizin"] },
    { word: "Apotheke", hints: ["Medizin", "Kaufen", "Pille", "Gesundheit", "Beratung"] },
    { word: "Arzt", hints: ["Heilt", "Patient", "Medizin", "Krankenhaus", "Sprechstunde"] },
    { word: "Krankenschwester", hints: ["Pflegt", "Patient", "Krankenhaus", "Hilft", "Uniform"] },
    { word: "Lehrer", hints: ["Unterrichtet", "Schule", "Klasse", "Wissen", "Tafel"] },
    { word: "Bäcker", hints: ["Backt", "Brot", "Kuchen", "Ofen", "Frisch"] },
    { word: "Koch", hints: ["Kocht", "Essen", "Küche", "Restaurant", "Schürze"] },
    { word: "Kellner", hints: ["Serviert", "Essen", "Restaurant", "Getränke", "Freundlich"] },
    { word: "Friseur", hints: ["Schneidet", "Haare", "Färbt", "Salon", "Schere"] },
    { word: "Mechaniker", hints: ["Repariert", "Auto", "Werkstatt", "Schraubt", "Motor"] },
    { word: "Pilot", hints: ["Fliegt", "Flugzeug", "Himmel", "Steuert", "Wolken"] },
    { word: "Gärtner", hints: ["Pflanzt", "Blumen", "Garten", "Pflegt", "Grün"] },
    { word: "Künstler", hints: ["Malt", "Zeichnet", "Kunst", "Kreativ", "Farben"] },
    { word: "Musiker", hints: ["Spielt", "Instrument", "Musik", "Singt", "Konzert"] },
    { word: "Sportler", hints: ["Trainiert", "Wettkampf", "Sport", "Bewegt", "Gewinnt"] },
    { word: "Schauspieler", hints: ["Spielt", "Rolle", "Bühne", "Film", "Theater"] },
    { word: "Sänger", hints: ["Singt", "Lied", "Stimme", "Bühne", "Musik"] },
    { word: "Tänzer", hints: ["Tanzt", "Bewegt", "Musik", "Bühne", "Rhythmus"] },
    { word: "Schreiner", hints: ["Holz", "Arbeitet", "Möbel", "Werkzeug", "Sägt"] },
    { word: "Maurer", hints: ["Mauert", "Steine", "Haus", "Bauen", "Zement"] },
    { word: "Maler", hints: ["Malt", "Wände", "Farbe", "Pinsel", "Haus"] },
    { word: "Klempner", hints: ["Rohre", "Repariert", "Wasser", "Heizung", "Werkzeug"] },
    { word: "Elektriker", hints: ["Strom", "Kabel", "Repariert", "Licht", "Sicher"] },
    { word: "Müllmann", hints: ["Müll", "Leert", "Sammelt", "Straße", "Sauber"] },
    { word: "Postbote", hints: ["Liefert", "Briefe", "Pakete", "Post", "Unterwegs"] },
    { word: "Anwalt", hints: ["Recht", "Berät", "Gesetz", "Gericht", "Vertritt"] },
    { word: "Richter", hints: ["Urteilt", "Gericht", "Gesetz", "Gerechtigkeit", "Fall"] },
    { word: "Student", hints: ["Studiert", "Uni", "Bücher", "Lernen", "Prüfung"] },
    { word: "Rentner", hints: ["Rente", "Freizeit", "Alter", "Nicht mehr", "Genießt"] },
    { word: "Baby", hints: ["Klein", "Weint", "Schläft", "Windel", "Lieb"] },
    { word: "Kind", hints: ["Spielt", "Lernt", "Wächst", "Eltern", "Jung"] },
    { word: "Teenager", hints: ["Jung", "Rebelliert", "Schule", "Freunde", "Musik"] },
    { word: "Erwachsener", hints: ["Arbeitet", "Verantwortung", "Selbstständig", "Reif", "Leben"] },
    { word: "Oma", hints: ["Großmutter", "Lieb", "Erzählt", "Kocht", "Familie"] },
    { word: "Opa", hints: ["Großvater", "Lieb", "Erzählt", "Bastelt", "Familie"] },
    { word: "Eltern", hints: ["Mutter", "Vater", "Erzieht", "Liebt", "Familie"] },
    { word: "Familie", hints: ["Zusammen", "Liebe", "Blut", "Haus", "Unterstützt"] },
    { word: "Freund", hints: ["Vertraut", "Hilft", "Redet", "Gemeinsam", "Lacht"] },
    { word: "Nachbar", hints: ["Nebenan", "Wohnt", "Hilft", "Grüßt", "Unbekannt"] },
    { word: "Tourist", hints: ["Reist", "Sieht", "Fremd", "Urlaub", "Kamera"] },
    { word: "Passant", hints: ["Geht", "Straße", "Sieht", "Vorbei", "Fremd"] },
    { word: "Kunde", hints: ["Kauft", "Zahlt", "Geschäft", "Will", "Bedient"] },
    { word: "Verkäufer", hints: ["Verkauft", "Berät", "Geschäft", "Hilft", "Freundlich"] },
    { word: "Chef", hints: ["Leitet", "Arbeit", "Entscheidet", "Gibt", "Anweisung"] },
    { word: "Kollege", hints: ["Arbeitet", "Zusammen", "Büro", "Hilft", "Team"] },
    { word: "Patient", hints: ["Krank", "Arzt", "Wartet", "Behandelt", "Genesung"] },
    { word: "Zeitung", hints: ["Lesen", "Nachrichten", "Papier", "Information", "Täglich"] },
    { word: "Magazin", hints: ["Lesen", "Bilder", "Interessen", "Wöchentlich", "Glanz"] },
    { word: "Radio", hints: ["Hören", "Musik", "Nachrichten", "Sender", "Spricht"] },
    { word: "Fernseher", hints: ["Schauen", "Bilder", "Ton", "Programm", "Wohnzimmer"] },
    { word: "Film", hints: ["Anschauen", "Geschichte", "Kino", "Popcorn", "Abenteuer"] },
    { word: "Serie", hints: ["Anschauen", "Folgen", "Wiederholt", "Charaktere", "Geschichte"] },
    { word: "Lied", hints: ["Singen", "Musik", "Text", "Melodie", "Tanzen"] },
    { word: "Instrument", hints: ["Musik", "Spielen", "Klang", "Töne", "Üben"] },
    { word: "Gitarre", hints: ["Saiten", "Spielt", "Musik", "Holz", "Akkord"] },
    { word: "Klavier", hints: ["Tasten", "Spielt", "Musik", "Groß", "Melodie"] },
    { word: "Schlagzeug", hints: ["Trommeln", "Spielt", "Musik", "Rhythmus", "Sticks"] },
    { word: "Flöte", hints: ["Bläst", "Spielt", "Musik", "Loch", "Holz"] },
    { word: "Geige", hints: ["Streichinstrument", "Spielt", "Musik", "Bogen", "Saiten"] },
    { word: "Trompete", hints: ["Blasinstrument", "Spielt", "Musik", "Blech", "Klang"] },
    { word: "Saxophon", hints: ["Blasinstrument", "Spielt", "Musik", "Jazz", "Metall"] },
    { word: "Kamera", hints: ["Foto", "Aufnimmt", "Bild", "Objektiv", "Knipsen"] },
    { word: "Album", hints: ["Fotos", "Erinnerungen", "Sammelt", "Blättern", "Papier"] },
    { word: "Bild", hints: ["Ansehen", "Erkennt", "Wand", "Rahmen", "Foto"] },
    { word: "Statue", hints: ["Figur", "Stein", "Kunst", "Steht", "Groß"] },
    { word: "Museum", hints: ["Kunst", "Geschichte", "Ausstellung", "Besucht", "Lernt"] },
    { word: "Galerie", hints: ["Kunst", "Bilder", "Verkauft", "Ausstellung", "Betrachtet"] },
    { word: "Kino", hints: ["Film", "Popcorn", "Dunkel", "Sitz", "Große Leinwand"] },
    { word: "Theater", hints: ["Bühne", "Schauspieler", "Stück", "Vorstellung", "Applaus"] },
    { word: "Zirkus", hints: ["Tiere", "Artisten", "Zelt", "Clown", "Staunen"] },
    { word: "Konzert", hints: ["Musik", "Live", "Bühne", "Sänger", "Laut"] },
    { word: "Sportplatz", hints: ["Spielt", "Sport", "Feld", "Stadion", "Team"] },
    { word: "Stadion", hints: ["Groß", "Zuschauer", "Sport", "Spielt", "Jubel"] },
    { word: "Schwimmbad", hints: ["Schwimmen", "Wasser", "Kühlen", "Badehose", "Chlor"] },
    { word: "Fitnessstudio", hints: ["Trainiert", "Muskeln", "Sport", "Geräte", "Schwitzt"] },
    { word: "Wanderweg", hints: ["Geht", "Natur", "Berg", "Pfad", "Wald"] },
    { word: "Zelt", hints: ["Campen", "Schlafen", "Natur", "Aufbauen", "Stoff"] },
    { word: "Schlafsack", hints: ["Schläft", "Warm", "Campen", "Kuschelig", "Rollst"] },
    { word: "Rucksack", hints: ["Tragen", "Wandern", "Gepäck", "Schulter", "Packt"] },
    { word: "Kompass", hints: ["Orientiert", "Richtung", "Norden", "Zeigt", "Wandern"] },
    { word: "Karte", hints: ["Zeigt", "Weg", "Land", "Orientiert", "Falten"] },
    { word: "Taschenlampe", hints: ["Licht", "Dunkel", "Leuchtet", "Batterie", "Trägt"] },
    { word: "Messer", hints: ["Schneidet", "Scharf", "Küche", "Werkzeug", "Griff"] },
    { word: "Axt", hints: ["Holz", "Spalten", "Scharf", "Wald", "Stiel"] },
    { word: "Säge", hints: ["Holz", "Sägt", "Scharf", "Werkzeug", "Zähne"] },
    { word: "Schraubenzieher", hints: ["Schraubt", "Dreht", "Werkzeug", "Spitze", "Griff"] },
    { word: "Zange", hints: ["Greift", "Hält", "Werkzeug", "Metall", "Draht"] },
    { word: "Schraube", hints: ["Dreht", "Hält", "Metall", "Holz", "Gewinde"] },
    { word: "Nagel", hints: ["Schlägt", "Hält", "Metall", "Holz", "Spitz"] },
    { word: "Klebeband", hints: ["Klebt", "Verbindet", "Rolle", "Repariert", "Dünn"] },
    { word: "Leim", hints: ["Klebt", "Verbindet", "Flüssig", "Trocknet", "Stark"] },
    { word: "Farbe", hints: ["Malt", "Streich", "Bunt", "Pinsel", "Wand"] },
    { word: "Pinsel", hints: ["Malt", "Farbe", "Borsten", "Griff", "Künstler"] },
    { word: "Eimer", hints: ["Füllt", "Wasser", "Farbe", "Trägt", "Reinigt"] },
    { word: "Leiter", hints: ["Steigt", "Hoch", "Arbeitet", "Holz", "Stufen"] },
    { word: "Handschuhe", hints: ["Schutz", "Hände", "Arbeit", "Winter", "Paar"] },
    { word: "Schutzbrille", hints: ["Augen", "Schützt", "Arbeit", "Glas", "Sicherheit"] },
    { word: "Helm", hints: ["Kopf", "Schutz", "Baustelle", "Hart", "Sicherheit"] },
    { word: "Maske", hints: ["Gesicht", "Schutz", "Atmet", "Stoff", "Verdeckt"] },
    { word: "Fahrrad", hints: ["Fährt", "Räder", "Pedale", "Lenker", "Klingel"] },
    { word: "Roller", hints: ["Fährt", "Räder", "Trittbrett", "Lenker", "Kind"] },
    { word: "Skateboard", hints: ["Fährt", "Brett", "Rollen", "Tricks", "Springt"] },
    { word: "Schlitten", hints: ["Rutschen", "Schnee", "Winter", "Holz", "Berg"] },
    { word: "Schlittschuh", hints: ["Eis", "Kufen", "Sport", "Winter", "Gleitet"] },
    { word: "Ski", hints: ["Schnee", "Brett", "Stöcke", "Berg", "Sport"] },
    { word: "Schneemann", hints: ["Schnee", "Kugel", "Karotte", "Arme", "Winter"] },
    { word: "Schneeflocke", hints: ["Schnee", "Klein", "Fällt", "Kristall", "Einzigartig"] },
    { word: "Eis", hints: ["Kalt", "Wasser", "Gefroren", "Rutschig", "Würfel"] },
    { word: "Gletscher", hints: ["Eis", "Groß", "Bewegt", "Berg", "Kalt"] },
    { word: "Wüste", hints: ["Sand", "Trocken", "Heiß", "Kaktus", "Kein Wasser"] },
    { word: "Oase", hints: ["Wasser", "Wüste", "Grün", "Palmen", "Erholung"] },
    { word: "Dschungel", hints: ["Grün", "Feucht", "Tiere", "Pflanzen", "Dick"] },
    { word: "Höhle", hints: ["Dunkel", "Stein", "Tiere", "Unterirdisch", "Kalt"] },
    { word: "Vulkan", hints: ["Berg", "Feuer", "Rauch", "Lava", "Ausbruch"] },
    { word: "Insel", hints: ["Meer", "Land", "Umgeben", "Strand", "Klein"] },
    { word: "Küstenlinie", hints: ["Meer", "Land", "Grenze", "Welle", "Strand"] },
    { word: "Klippe", hints: ["Steil", "Abgrund", "Meer", "Felsen", "Hoch"] },
    { word: "Tal", hints: ["Zwischen", "Berge", "Fluss", "Grün", "Tief"] },
    { word: "Ebene", hints: ["Flach", "Weit", "Land", "Feld", "Aussicht"] },
    { word: "Hügel", hints: ["Klein", "Berg", "Sanft", "Grün", "Steigung"] },
    { word: "See", hints: ["Wasser", "Still", "Fisch", "Boot", "Ufer"] },
    { word: "Teich", hints: ["Klein", "Wasser", "Frosch", "Garten", "Seerose"] },
    { word: "Bach", hints: ["Klein", "Fluss", "Plätschert", "Wasser", "Steine"] },
    { word: "Wasserfall", hints: ["Wasser", "Fällt", "Laut", "Natur", "Höhe"] },
    { word: "Quelle", hints: ["Wasser", "Entsteht", "Frisch", "Boden", "Fließt"] },
    { word: "Brunnen", hints: ["Wasser", "Spendet", "Stadt", "Zieht", "Trinkt"] },
    { word: "Regenbogen", hints: ["Farben", "Himmel", "Regen", "Sonne", "Bogen"] },
    { word: "Blitz", hints: ["Donner", "Licht", "Himmel", "Gewitter", "Schnell"] },
    { word: "Donner", hints: ["Laut", "Geräusch", "Gewitter", "Himmel", "Rollend"] },
    { word: "Hagel", hints: ["Eis", "Fällt", "Regen", "Klein", "Schlägt"] },
    { word: "Nebel", hints: ["Dicht", "Sieht", "Schlecht", "Grau", "Feucht"] },
    { word: "Tau", hints: ["Morgen", "Tropfen", "Gras", "Feucht", "Glänzt"] },
    { word: "Frost", hints: ["Kalt", "Eis", "Pflanzen", "Weiß", "Glatt"] },
    { word: "Schneesturm", hints: ["Schnee", "Wind", "Stark", "Winter", "Dunkel"] },
    { word: "Lawine", hints: ["Schnee", "Rutschen", "Berg", "Gefährlich", "Schnell"] },
    { word: "Tornado", hints: ["Sturm", "Wirbel", "Zerstört", "Wind", "Trichter"] },
    { word: "Hurrikan", hints: ["Sturm", "Meer", "Groß", "Wind", "Regen"] },
    { word: "Erdbeben", hints: ["Boden", "Schüttelt", "Risse", "Gefährlich", "Zerstört"] },
    { word: "Vulkanausbruch", hints: ["Feuer", "Lava", "Asche", "Rauch", "Gefährlich"] },
    { word: "Flut", hints: ["Wasser", "Steigt", "Überflutet", "Hoch", "Gefährlich"] },
    { word: "Tsunami", hints: ["Welle", "Groß", "Meer", "Zerstört", "Gefährlich"] },
    { word: "Dürre", hints: ["Trocken", "Kein Wasser", "Pflanzen", "Sterben", "Heiß"] },
    { word: "Überschwemmung", hints: ["Wasser", "Land", "Bedeckt", "Regen", "Zerstört"] },
    { word: "Sonnenaufgang", hints: ["Morgen", "Sonne", "Steigt", "Licht", "Beginnt"] },
    { word: "Sonnenuntergang", hints: ["Abend", "Sonne", "Sinkt", "Dunkel", "Endet"] },
    { word: "Dämmerung", hints: ["Licht", "Zwischen", "Tag", "Nacht", "Grau"] },
    { word: "Morgen", hints: ["Früh", "Tag", "Erwachen", "Kaffee", "Beginnt"] },
    { word: "Mittag", hints: ["Mitte", "Tag", "Sonne", "Essen", "Kurz"] },
    { word: "Abend", hints: ["Dunkel", "Tag", "Endet", "Schlafen", "Ruhe"] },
    { word: "Nacht", hints: ["Dunkel", "Schlafen", "Mond", "Sterne", "Still"] },
    { word: "Woche", hints: ["Tage", "Sieben", "Arbeit", "Freizeit", "Kalender"] },
    { word: "Monat", hints: ["Wochen", "Vier", "Kalender", "Jahreszeit", "Lang"] },
    { word: "Jahr", hints: ["Monate", "Zwölf", "Geburtstag", "Neujahr", "Vergeht"] },
    { word: "Jahreszeit", hints: ["Frühling", "Sommer", "Herbst", "Winter", "Wechselt"] },
    { word: "Frühling", hints: ["Blumen", "Grün", "Warm", "Wachstum", "Beginnt"] },
    { word: "Sommer", hints: ["Heiß", "Sonne", "Urlaub", "Schwimmen", "Blüht"] },
    { word: "Herbst", hints: ["Blätter", "Fallen", "Kalt", "Regen", "Ernte"] },
    { word: "Winter", hints: ["Kalt", "Schnee", "Eis", "Warm", "Weihnachten"] },
    { word: "Feiertag", hints: ["Frei", "Feiern", "Besonders", "Familie", "Ruhe"] },
    { word: "Geburtstag", hints: ["Feiern", "Kuchen", "Geschenke", "Kerzen", "Älter"] },
    { word: "Hochzeit", hints: ["Heirat", "Liebe", "Feiern", "Ring", "Paar"] },
    { word: "Beerdigung", hints: ["Trauer", "Tod", "Abschied", "Erde", "Still"] },
    { word: "Party", hints: ["Feiern", "Musik", "Tanzen", "Freunde", "Spaß"] },
    { word: "Konzert", hints: ["Musik", "Live", "Bühne", "Sänger", "Laut"] },
    { word: "Festival", hints: ["Musik", "Groß", "Draußen", "Feiern", "Viele"] },
    { word: "Markt", hints: ["Kaufen", "Verkaufen", "Frisch", "Obst", "Gemüse"] },
    { word: "Supermarkt", hints: ["Einkaufen", "Lebensmittel", "Waren", "Regale", "Wagen"] },
    { word: "Geschäft", hints: ["Kaufen", "Waren", "Verkäufer", "Kunde", "Geld"] },
    { word: "Restaurant", hints: ["Essen", "Trinken", "Koch", "Kellner", "Tisch"] },
    { word: "Cafe", hints: ["Kaffee", "Kuchen", "Treffen", "Sprechen", "Gemütlich"] },
    { word: "Bar", hints: ["Getränke", "Abend", "Freunde", "Musik", "Sprechen"] },
    { word: "Kino", hints: ["Film", "Popcorn", "Dunkel", "Leinwand", "Sitz"] },
    { word: "Theater", hints: ["Bühne", "Schauspieler", "Stück", "Vorhang", "Applaus"] },
    { word: "Museum", hints: ["Kunst", "Geschichte", "Ausstellung", "Betrachtet", "Lernt"] },
    { word: "Bibliothek", hints: ["Bücher", "Lesen", "Ausleihen", "Ruhe", "Wissen"] },
    { word: "Bank", hints: ["Geld", "Einzahlen", "Abheben", "Konto", "Sicher"] },
    { word: "Postamt", hints: ["Briefe", "Pakete", "Verschicken", "Briefmarke", "Gelb"] },
    { word: "Polizeistation", hints: ["Polizei", "Hilft", "Schützt", "Gesetz", "Meldet"] },
    { word: "Feuerwache", hints: ["Feuerwehr", "Löscht", "Einsatz", "Auto", "Helden"] },
    { word: "Krankenhaus", hints: ["Arzt", "Krank", "Heilt", "Notfall", "Medizin"] },
    { word: "Apotheke", hints: ["Medizin", "Kaufen", "Rezept", "Berät", "Gesundheit"] },
    { word: "Arztpraxis", hints: ["Arzt", "Patient", "Untersucht", "Sprechstunde", "Heilt"] },
    { word: "Tierarzt", hints: ["Tier", "Krank", "Heilt", "Spritze", "Untersucht"] },
    { word: "Friseursalon", hints: ["Haare", "Schneiden", "Färben", "Waschen", "Styling"] },
    { word: "Autowerkstatt", hints: ["Auto", "Repariert", "Motor", "Reifen", "Schraubt"] },
    { word: "Tankstelle", hints: ["Auto", "Tankt", "Sprit", "Benzin", "Bezahlt"] },
    { word: "Bahnhof", hints: ["Zug", "Fährt", "Gleis", "Reisen", "Warten"] },
    { word: "Flughafen", hints: ["Flugzeug", "Fliegt", "Reisen", "Abflug", "Landung"] },
    { word: "Hafen", hints: ["Schiff", "Anker", "Wasser", "Boot", "Transport"] },
    { word: "Brücke", hints: ["Überquert", "Fluss", "Verbindet", "Weg", "Bogen"] },
    { word: "Tunnel", hints: ["Unter", "Berg", "Dunkel", "Fährt", "Lang"] },
    { word: "Parkplatz", hints: ["Auto", "Parkt", "Stellplatz", "Bezahlt", "Such"] },
    { word: "Spielplatz", hints: ["Kinder", "Spielen", "Schaukel", "Rutsche", "Sand"] },
    { word: "Garten", hints: ["Pflanzt", "Blumen", "Grün", "Erde", "Gießt"] },
    { word: "Bauernhof", hints: ["Tiere", "Landwirtschaft", "Feld", "Ernte", "Traktor"] },
    { word: "Wald", hints: ["Bäume", "Grün", "Tiere", "Dunkel", "Pilze"] },
    { word: "Fluss", hints: ["Wasser", "Fließt", "Lang", "Ufer", "Fisch"] },
    { word: "Meer", hints: ["Salz", "Wasser", "Groß", "Wellen", "Strand"] },
    { word: "See", hints: ["Wasser", "Süß", "Still", "Ufer", "Boot"] },
    { word: "Berg", hints: ["Hoch", "Steil", "Wandern", "Aussicht", "Gipfel"] },
    { word: "Wüste", hints: ["Trocken", "Sand", "Heiß", "Kaktus", "Kamelt"] },
    { word: "Oase", hints: ["Wasser", "Wüste", "Grün", "Palmen", "Schatten"] },
    { word: "Vulkan", hints: ["Feuer", "Spuckt", "Berg", "Lava", "Raucht"] },
    { word: "Insel", hints: ["Meer", "Umgeben", "Land", "Klein", "Strand"] },
    { word: "Höhle", hints: ["Dunkel", "Fels", "Tiere", "Unterirdisch", "Kalt"] },
    { word: "Himmel", hints: ["Blau", "Wolken", "Sonne", "Sterne", "Weit"] },
    { word: "Sonne", hints: ["Warm", "Licht", "Scheint", "Tag", "Rund"] },
    { word: "Mond", hints: ["Nacht", "Leuchtet", "Sichel", "Himmel", "Grau"] },
    { word: "Stern", hints: ["Funkelt", "Himmel", "Nacht", "Klein", "Leuchtet"] },
    { word: "Wolke", hints: ["Himmel", "Weiß", "Regen", "Form", "Zieht"] },
    { word: "Regen", hints: ["Nass", "Fällt", "Schirm", "Pfütze", "Tropfen"] },
    { word: "Schnee", hints: ["Kalt", "Weiß", "Fällt", "Flocke", "Winter"] },
    { word: "Wind", hints: ["Bläst", "Luft", "Bewegt", "Kalt", "Sturm"] },
    { word: "Nebel", hints: ["Dicht", "Sieht", "Schlecht", "Grau", "Feucht"] },
    { word: "Blitz", hints: ["Himmel", "Leuchtet", "Laut", "Gefährlich", "Elektrisch"] },
    { word: "Donner", hints: ["Laut", "Himmel", "Grollt", "Gewitter", "Rollend"] },
    { word: "Regenbogen", hints: ["Farben", "Bogen", "Sonne", "Regen", "Wunder"] },
    { word: "Strand", hints: ["Sand", "Meer", "Sonne", "Liegt", "Baden"] },
    { word: "Welle", hints: ["Meer", "Bewegt", "Wasser", "Rollend", "Brandung"] },
    { word: "Muschel", hints: ["Meer", "Schale", "Leer", "Sammelt", "Hart"] },
    { word: "Seestern", hints: ["Meer", "Fünf", "Arme", "Tier", "Rot"] },
    { word: "Fisch", hints: ["Schwimmt", "Wasser", "Flossen", "Schuppen", "Angelt"] },
    { word: "Vogel", hints: ["Fliegt", "Federn", "Nest", "Zwitschert", "Flügel"] },
    { word: "Hund", hints: ["Bellt", "Haustier", "Loyal", "Spielt", "Geht"] },
    { word: "Katze", hints: ["Miau", "Haustier", "Kratzt", "Schläft", "Maus"] },
    { word: "Pferd", hints: ["Reiten", "Tier", "Wiehert", "Stall", "Huf"] },
    { word: "Kuh", hints: ["Milch", "Muuht", "Tier", "Weide", "Gras"] },
    { word: "Schwein", hints: ["Grunzt", "Tier", "Schlamm", "Rosa", "Fleisch"] },
    { word: "Huhn", hints: ["Gackert", "Ei", "Tier", "Fliegt", "Stall"] },
    { word: "Schaf", hints: ["Blökt", "Wolle", "Tier", "Weide", "Lamm"] },
    { word: "Ziege", hints: ["Mäh", "Klettert", "Tier", "Hörner", "Bart"] },
    { word: "Ente", hints: ["Quakt", "Schwimmt", "Tier", "Wasser", "Fliegt"] },
    { word: "Gans", hints: ["Schnattert", "Fliegt", "Tier", "Wasser", "Groß"] },
    { word: "Maus", hints: ["Klein", "Piept", "Tier", "Käse", "Versteckt"] },
    { word: "Ratte", hints: ["Groß", "Nagt", "Tier", "Schwanz", "Keller"] },
    { word: "Hase", hints: ["Hüpft", "Ohren", "Tier", "Möhre", "Fell"] },
    { word: "Fuchs", hints: ["Rot", "Schlau", "Tier", "Wald", "Jagt"] },
    { word: "Wolf", hints: ["Heult", "Rudel", "Tier", "Wald", "Jagt"] },
    { word: "Bär", hints: ["Groß", "Honig", "Tier", "Wald", "Schläft"] },
    { word: "Löwe", hints: ["Brüllt", "König", "Tier", "Savanne", "Mähne"] },
    { word: "Tiger", hints: ["Streifen", "Jagt", "Tier", "Dschungel", "Groß"] },
    { word: "Elefant", hints: ["Rüssel", "Groß", "Tier", "Ohren", "Dickhäuter"] },
    { word: "Affe", hints: ["Klettert", "Banane", "Tier", "Dschungel", "Schwanz"] },
    { word: "Krokodil", hints: ["Zähne", "Schwimmt", "Tier", "Fluss", "Reptil"] },
    { word: "Schlange", hints: ["Kriecht", "Gift", "Tier", "Züngelt", "Reptil"] },
    { word: "Spinne", hints: ["Netz", "Acht Beine", "Tier", "Krabbe", "Webt"] },
    { word: "Biene", hints: ["Summt", "Honig", "Sticht", "Blume", "Fliegt"] },
    { word: "Wespe", hints: ["Summt", "Sticht", "Gelb", "Fliegt", "Nest"] },
    { word: "Ameise", hints: ["Klein", "Arbeitet", "Kolonie", "Kriecht", "Fleißig"] },
    { word: "Mücke", hints: ["Sticht", "Juckt", "Klein", "Fliegt", "Blut"] },
    { word: "Schmetterling", hints: ["Fliegt", "Bunt", "Blume", "Raupe", "Zart"] },
    { word: "Regenwurm", hints: ["Kriecht", "Erde", "Klein", "Fischköder", "Nass"] },
    { word: "Eule", hints: ["Nacht", "Fliegt", "Augen", "Ruft", "Klug"] },
    { word: "Adler", hints: ["Fliegt", "Hoch", "Jagt", "Scharfe Augen", "Kralle"] },
    { word: "Taube", hints: ["Fliegt", "Frieden", "Stadt", "Gurrt", "Füttert"] },
    { word: "Spatz", hints: ["Klein", "Zwitschert", "Stadt", "Fliegt", "Füttert"] },
    { word: "Rabe", hints: ["Schwarz", "Kräht", "Klug", "Fliegt", "Groß"] },
    { word: "Fledermaus", hints: ["Fliegt", "Nacht", "Hängt", "Schläft", "Ultraschall"] },
    { word: "Delphin", hints: ["Schwimmt", "Springt", "Intelligent", "Meer", "Spielt"] },
    { word: "Wal", hints: ["Groß", "Schwimmt", "Meer", "Fontäne", "Säugetier"] },
    { word: "Robbe", hints: ["Schwimmt", "Meer", "Fisch", "Liegt", "Flossen"] },
    { word: "Pinguin", hints: ["Schwimmt", "Geht", "Eis", "Schwarz", "Fliegt nicht"] },
    { word: "Eisbär", hints: ["Kalt", "Eis", "Jagt", "Weiß", "Schwimmt"] },
    { word: "Kamel", hints: ["Wüste", "Höcker", "Transport", "Trinkt", "Trocken"] },
    { word: "Känguru", hints: ["Springt", "Beutel", "Australien", "Groß", "Schwanz"] },
    { word: "Koala", hints: ["Baum", "Eukalyptus", "Schläft", "Australien", "Gemütlich"] },
    { word: "Panda", hints: ["Bambus", "Schwarz-Weiß", "China", "Selten", "Bär"] },
    { word: "Zebra", hints: ["Streifen", "Pferd", "Afrika", "Herde", "Wild"] },
    { word: "Giraffe", hints: ["Hals", "Lang", "Afrika", "Punkte", "Baum"] },
    { word: "Nashorn", hints: ["Horn", "Groß", "Afrika", "Dickhäuter", "Gefährdet"] },
    { word: "Nilpferd", hints: ["Wasser", "Groß", "Afrika", "Schwimmt", "Fluss"] },
    { word: "Affe", hints: ["Klettert", "Banane", "Dschungel", "Baum", "Schwanz"] },
    { word: "Faultier", hints: ["Langsam", "Hängt", "Baum", "Dschungel", "Schläft"] },
    { word: "Frosch", hints: ["Springt", "Grün", "Teich", "Quakt", "Nass"] },
    { word: "Kröte", hints: ["Springt", "Braun", "Haut", "Feucht", "Garten"] },
    { word: "Eidechse", hints: ["Kriecht", "Sonnte", "Reptil", "Schwanz", "Klein"] },
    { word: "Schildkröte", hints: ["Panzer", "Langsam", "Meer", "Land", "Alt"] },
    { word: "Hai", hints: ["Scharf", "Schwimmt", "Meer", "Gefährlich", "Flosse"] },
    { word: "Krokodil", hints: ["Fluss", "Groß", "Zähne", "Schwimmt", "Reptil"] },
    { word: "Gott", hints: ["Glauben", "Himmel", "Beten", "Allmächtig", "Schöpfer"] },
    { word: "Engel", hints: ["Flügel", "Himmel", "Gut", "Bote", "Schutz"] },
    { word: "Teufel", hints: ["Böse", "Hölle", "Rot", "Hörner", "Verführt"] },
    { word: "Geist", hints: ["Unsichtbar", "Spukt", "Haus", "Tot", "Durchsichtig"] },
    { word: "Hexe", hints: ["Zaubert", "Besen", "Hut", "Böse", "Kessel"] },
    { word: "Fee", hints: ["Zaubert", "Flügel", "Gut", "Staub", "Klein"] },
    { word: "Drache", hints: ["Fliegt", "Feuer", "Groß", "Schuppen", "Legende"] },
    { word: "Einhorn", hints: ["Horn", "Pferd", "Rein", "Glänzt", "Legende"] },
    { word: "Zwerg", hints: ["Klein", "Bart", "Bergbau", "Gold", "Stark"] },
    { word: "Riese", hints: ["Groß", "Stark", "Legende", "Mächtig", "Furcht"] },
    { word: "Prinz", hints: ["König", "Schön", "Reitet", "Schloss", "Heiratet"] },
    { word: "Prinzessin", hints: ["König", "Schön", "Schloss", "Heiratet", "Krone"] },
    { word: "König", hints: ["Krone", "Regiert", "Schloss", "Mächtig", "Zepter"] },
    { word: "Königin", hints: ["Krone", "Regiert", "Schloss", "Mächtig", "Eleganz"] },
    { word: "Ritter", hints: ["Kämpft", "Schwert", "Rüstung", "Pferd", "Tapfer"] },
    { word: "Zauberer", hints: ["Zaubert", "Stab", "Magie", "Altert", "Weise"] },
    { word: "Kobold", hints: ["Klein", "Grün", "Gold", "Versteckt", "Listig"] },
    { word: "Elf", hints: ["Spitzohren", "Wald", "Magie", "Anmutig", "Lang"] },
    { word: "Vampir", hints: ["Blut", "Nacht", "Sarg", "Zähne", "Fledermaus"] },
    { word: "Werwolf", hints: ["Mond", "Haare", "Mensch", "Tier", "Jagt"] },
    { word: "Zombie", hints: ["Untot", "Geht", "Hirn", "Langsam", "Zerstört"] },
    { word: "Mumie", hints: ["Verband", "Ägypten", "Tot", "Geht", "Fluch"] },
    { word: "Monster", hints: ["Schreckt", "Groß", "Furcht", "Versteckt", "Böse"] },
    { word: "Geist", hints: ["Spukt", "Unsichtbar", "Haus", "Kalt", "Erschreckt"] },
    { word: "Piraten", hints: ["Schiff", "Schatz", "Meer", "Plündert", "Haken"] },
    { word: "Cowboy", hints: ["Pferd", "Hut", "Westen", "Reitet", "Lasso"] },
    { word: "Indianer", hints: ["Zelt", "Fell", "Pferd", "Krieger", "Stamm"] },
    { word: "Astronaut", hints: ["Weltall", "Rakete", "Helm", "Schwebt", "Sterne"] },
    { word: "Detektiv", hints: ["Sucht", "Hinweis", "Löst", "Fall", "Lupe"] },
    { word: "Forscher", hints: ["Entdeckt", "Wissen", "Labor", "Neues", "Experiment"] },
    { word: "Professor", hints: ["Lehrt", "Uni", "Klug", "Bücher", "Wissen"] },
    { word: "Koch", hints: ["Kocht", "Essen", "Küche", "Schmeckt", "Rezept"] },
    { word: "Bäcker", hints: ["Backt", "Brot", "Kuchen", "Ofen", "Duft"] },
    { word: "Metzger", hints: ["Fleisch", "Schneidet", "Wurst", "Kühl", "Hackt"] },
    { word: "Fischer", hints: ["Angelt", "Fisch", "Meer", "Boot", "Netz"] },
    { word: "Jäger", hints: ["Jagt", "Wald", "Tier", "Waffe", "Fell"] },
    { word: "Bauer", hints: ["Feld", "Tiere", "Ernte", "Traktor", "Land"] },
    { word: "Hirte", hints: ["Schafe", "Hund", "Weide", "Passen", "Stock"] },
    { word: "Holzfäller", hints: ["Holz", "Sägt", "Baum", "Axt", "Wald"] },
    { word: "Schneider", hints: ["Näht", "Stoff", "Kleidung", "Nadel", "Faden"] },
    { word: "Schuhmacher", hints: ["Schuhe", "Repariert", "Leder", "Näht", "Leisten"] },
    { word: "Juwelier", hints: ["Schmuck", "Glänzt", "Verkauft", "Gold", "Diamant"] },
    { word: "Uhrmacher", hints: ["Uhr", "Repariert", "Zeit", "Klein", "Genau"] },
    { word: "Gärtner", hints: ["Pflanzt", "Blumen", "Garten", "Grün", "Schaufel"] },
    { word: "Architekt", hints: ["Gebäude", "Plant", "Zeichnet", "Haus", "Baustelle"] },
    { word: "Ingenieur", hints: ["Baut", "Technik", "Problem", "Löst", "Rechnet"] },
    { word: "Wissenschaftler", hints: ["Forscht", "Labor", "Experiment", "Entdeckt", "Klug"] },
    { word: "Chemiker", hints: ["Stoffe", "Experiment", "Labor", "Reagiert", "Mischung"] },
    { word: "Physiker", hints: ["Natur", "Kräfte", "Universum", "Rechnet", "Forscht"] },
    { word: "Biologe", hints: ["Leben", "Tiere", "Pflanzen", "Zellen", "Natur"] },
    { word: "Historiker", hints: ["Geschichte", "Vergangenheit", "Erzählt", "Lernt", "Daten"] },
    { word: "Journalist", hints: ["Schreibt", "Nachrichten", "Interview", "Reist", "Information"] },
    { word: "Fotograf", hints: ["Macht", "Fotos", "Kamera", "Bild", "Blende"] },
    { word: "Maler", hints: ["Malt", "Leinwand", "Farbe", "Pinsel", "Kunst"] },
    { word: "Bildhauer", hints: ["Meißelt", "Stein", "Formt", "Kunst", "Skulptur"] },
    { word: "Schriftsteller", hints: ["Schreibt", "Bücher", "Geschichten", "Wörter", "Fantasiert"] },
    { word: "Dichter", hints: ["Schreibt", "Gedichte", "Reime", "Gefühle", "Wörter"] },
    { word: "Komponist", hints: ["Schreibt", "Musik", "Noten", "Melodie", "Spielt"] },
    { word: "Dirigent", hints: ["Leitet", "Orchester", "Taktstock", "Musik", "Rhythmus"] },
    { word: "Sänger", hints: ["Singt", "Lied", "Stimme", "Bühne", "Mikrofon"] },
    { word: "Tänzer", hints: ["Tanzt", "Musik", "Bewegt", "Bühne", "Rhythmus"] },
    { word: "Sportler", hints: ["Trainiert", "Wettkampf", "Gewinnt", "Bewegt", "Körper"] },
    { word: "Fußballspieler", hints: ["Spielt", "Ball", "Tor", "Feld", "Team"] },
    { word: "Basketballspieler", hints: ["Spielt", "Korb", "Ball", "Dribbelt", "Team"] },
    { word: "Tennisspieler", hints: ["Spielt", "Schläger", "Ball", "Netz", "Feld"] },
    { word: "Schwimmer", hints: ["Schwimmt", "Wasser", "Pool", "Kraulen", "Bahn"] },
    { word: "Läufer", hints: ["Rennt", "Bahn", "Schnell", "Sport", "Marathon"] },
    { word: "Skifahrer", hints: ["Fährt", "Ski", "Schnee", "Berg", "Stöcke"] },
    { word: "Eisläufer", hints: ["Gleitet", "Eis", "Kufen", "Pirouette", "Sport"] },
    { word: "Boxer", hints: ["Kämpft", "Faust", "Ring", "Schlägt", "Stark"] },
    { word: "Judoka", hints: ["Kämpft", "Matte", "Wurf", "Gürtel", "Disziplin"] },
    { word: "Ringer", hints: ["Kämpft", "Matte", "Greift", "Stark", "Hält"] },
    { word: "Fechter", hints: ["Ficht", "Degen", "Maske", "Schnell", "Ziel"] },
    { word: "Turner", hints: ["Turnt", "Gerät", "Körper", "Flexibel", "Stark"] },
    { word: "Akrobat", hints: ["Körper", "Gelenkig", "Zeigt", "Schwer", "Balance"] },
    { word: "Zauberer", hints: ["Zeigt", "Tricks", "Verblüfft", "Kaninchen", "Hut"] },
    { word: "Clown", hints: ["Lacht", "Schminke", "Zirkus", "Nase", "Macht Spaß"] },
    { word: "Jongleur", hints: ["Wirft", "Bälle", "Balance", "Geschick", "Fängt"] },
    { word: "Artisten", hints: ["Zirkus", "Zeigt", "Mutig", "Können", "Publikum"] },
    { word: "Puppenspieler", hints: ["Spielt", "Puppen", "Fäden", "Bühne", "Erzählt"] },
    { word: "Gaukler", hints: ["Macht", "Kunststücke", "Unterhält", "Mittelalter", "Wandert"] },
    { word: "Alchemist", hints: ["Gold", "Macht", "Trank", "Geheimnis", "Mittelalter"] },
    { word: "Weiser", hints: ["Klug", "Alt", "Berät", "Wissen", "Erfahren"] },
    { word: "Narr", hints: ["Lustig", "Macht", "Scherze", "Hof", "Unterhält"] },
    { word: "König", hints: ["Krone", "Thron", "Herrscht", "Schloss", "Reich"] },
    { word: "Kaiser", hints: ["Noch", "Größer", "Mächtig", "Reich", "Krone"] },
    { word: "Prinz", hints: ["Sohn", "König", "Thronfolger", "Heiratet", "Schön"] },
    { word: "Prinzessin", hints: ["Tochter", "Königin", "Heiratet", "Schön", "Schloss"] },
    { word: "Ritter", hints: ["Kämpft", "Pferd", "Rüstung", "Schwert", "Ehre"] },
    { word: "Burg", hints: ["Stein", "Alt", "König", "Verteidigt", "Mauer"] },
    { word: "Schloss", hints: ["König", "Schön", "Groß", "Garten", "Turm"] },
    { word: "Turm", hints: ["Hoch", "Spitz", "Burg", "Uhr", "Aussicht"] },
    { word: "Graben", hints: ["Wasser", "Burg", "Schützt", "Tief", "Brücke"] },
    { word: "Mauer", hints: ["Schützt", "Stein", "Fest", "Burg", "Grenze"] },
    { word: "Kerker", hints: ["Dunkel", "Gefangen", "Unten", "Feucht", "Gitter"] },
    { word: "Thron", hints: ["Sitz", "König", "Macht", "Groß", "Glänzt"] },
    { word: "Zepter", hints: ["Stab", "König", "Macht", "Symbol", "Gold"] },
    { word: "Krone", hints: ["Kopf", "König", "Gold", "Schmuck", "Symbol"] },
    { word: "Schwert", hints: ["Kämpft", "Scharf", "Ritter", "Metall", "Griff"] },
    { word: "Schild", hints: ["Schützt", "Ritter", "Rund", "Holz", "Verteidigt"] },
    { word: "Rüstung", hints: ["Trägt", "Schützt", "Metall", "Ritter", "Schwer"] },
    { word: "Bogen", hints: ["Schießt", "Pfeil", "Jagt", "Holz", "Sehne"] },
    { word: "Pfeil", hints: ["Fliegt", "Spitz", "Bogen", "Treffer", "Feder"] },
    { word: "Axt", hints: ["Holz", "Schlägt", "Scharf", "Waffe", "Stiel"] },
    { word: "Speer", hints: ["Wirft", "Spitz", "Waffe", "Lang", "Jagt"] },
    { word: "Morgenstern", hints: ["Kugel", "Stacheln", "Waffe", "Kette", "Mittelalter"] },
    { word: "Katapult", hints: ["Wirft", "Steine", "Belagert", "Waffe", "Groß"] },
    { word: "Trebuchet", hints: ["Wirft", "Steine", "Belagert", "Groß", "Mittelalter"] },
    { word: "Ritterturnier", hints: ["Kämpft", "Pferd", "Lanze", "Ehre", "Zuschauer"] },
    { word: "Turnier", hints: ["Wettkampf", "Sport", "Spiele", "Gewinnt", "Zuschauer"] },
    { word: "Fest", hints: ["Feiern", "Musik", "Essen", "Tanzen", "Fröhlich"] },
    { word: "Ball", hints: ["Tanzen", "Kleid", "Musik", "Elegant", "Gesellschaft"] },
    { word: "Maskerade", hints: ["Maske", "Kostüm", "Täuscht", "Feiern", "Geheimnis"] },
    { word: "Bankett", hints: ["Essen", "Groß", "Feiern", "Tisch", "Viele"] },
    { word: "Handel", hints: ["Kaufen", "Verkaufen", "Waren", "Geld", "Tauscht"] },
    { word: "Münze", hints: ["Zahlt", "Metall", "Klein", "Wert", "Tasche"] },
    { word: "Schatz", hints: ["Gold", "Versteckt", "Reichtum", "Truhe", "Karte"] },
    { word: "Juwel", hints: ["Glänzt", "Stein", "Schmuck", "Wertvoll", "Farbig"] },
    { word: "Gold", hints: ["Glänzt", "Metall", "Wertvoll", "Schmuck", "Münze"] },
    { word: "Silber", hints: ["Glänzt", "Metall", "Wertvoll", "Schmuck", "Münze"] },
    { word: "Diamant", hints: ["Funkelt", "Hart", "Wertvoll", "Schmuck", "Edelstein"] },
    { word: "Smaragd", hints: ["Grün", "Glänzt", "Edelstein", "Schmuck", "Wertvoll"] },
    { word: "Rubin", hints: ["Rot", "Glänzt", "Edelstein", "Schmuck", "Wertvoll"] },
    { word: "Saphir", hints: ["Blau", "Glänzt", "Edelstein", "Schmuck", "Wertvoll"] },
    { word: "Perle", hints: ["Weiß", "Glänzt", "Muschel", "Schmuck", "Rund"] },
    { word: "Seide", hints: ["Glatt", "Stoff", "Schön", "Luxus", "Weich"] },
    { word: "Baumwolle", hints: ["Stoff", "Weich", "Kleidung", "Pflanze", "Natur"] },
    { word: "Leder", hints: ["Haut", "Tier", "Stark", "Schuhe", "Tasche"] },
    { word: "Wolle", hints: ["Schaf", "Warm", "Stoff", "Strickt", "Winter"] },
    { word: "Holz", hints: ["Baum", "Brennt", "Baut", "Möbel", "Hart"] },
    { word: "Stein", hints: ["Hart", "Schwer", "Baut", "Fels", "Grau"] },
    { word: "Metall", hints: ["Hart", "Glänzt", "Baut", "Werkzeug", "Eisen"] },
    { word: "Glas", hints: ["Zerbrechlich", "Durchsichtig", "Fenster", "Trinken", "Spiegel"] },
    { word: "Plastik", hints: ["Leicht", "Formbar", "Recycelt", "Flasche", "Spielzeug"] },
    { word: "Papier", hints: ["Schreibt", "Druckt", "Blatt", "Baum", "Faltet"] },
    { word: "Tinte", hints: ["Schreibt", "Farbe", "Stift", "Flasche", "Fleckt"] },
    { word: "Bleistift", hints: ["Schreibt", "Holz", "Spitze", "Zeichnet", "Radiergummi"] },
    { word: "Kreide", hints: ["Schreibt", "Tafel", "Weiß", "Bröselt", "Zeichnet"] },
    { word: "Stift", hints: ["Schreibt", "Tinte", "Kappe", "Farbe", "Hand"] },
    { word: "Buch", hints: ["Lesen", "Seiten", "Wissen", "Geschichte", "Autor"] },
    { word: "Zeitung", hints: ["Lesen", "Nachrichten", "Papier", "Täglich", "Information"] },
    { word: "Karte", hints: ["Zeigt", "Weg", "Land", "Orientiert", "Faltet"] },
    { word: "Brief", hints: ["Schreibt", "Nachricht", "Umschlag", "Post", "Sendet"] },
    { word: "Foto", hints: ["Macht", "Bild", "Kamera", "Erinnerung", "Rahmen"] },
    { word: "Gemälde", hints: ["Malt", "Leinwand", "Kunst", "Farben", "Rahmen"] },
    { word: "Skulptur", hints: ["Formt", "Stein", "Kunst", "Figur", "Meißelt"] },
    { word: "Lied", hints: ["Singt", "Musik", "Melodie", "Text", "Tanzt"] },
    { word: "Musik", hints: ["Hört", "Spielt", "Klang", "Töne", "Rhythmus"] },
    { word: "Tanz", hints: ["Bewegt", "Musik", "Rhythmus", "Körper", "Schritt"] },
    { word: "Sport", hints: ["Bewegt", "Spielt", "Körper", "Gesund", "Regel"] },
    { word: "Spiel", hints: ["Spielt", "Spaß", "Regeln", "Gewinnt", "Verliert"] },
    { word: "Witz", hints: ["Lacht", "Lustig", "Erzählt", "Geschichte", "Punkt"] },
    { word: "Rätsel", hints: ["Denkt", "Löst", "Frage", "Antwort", "Schwer"] },
    { word: "Märchen", hints: ["Erzählt", "Kinder", "Prinzessin", "Gut", "Böse"] },
    { word: "Legende", hints: ["Alt", "Geschichte", "Erzählt", "Helden", "Wahr"] },
    { word: "Mythos", hints: ["Alt", "Geschichte", "Götter", "Erzählt", "Glauben"] },
    { word: "Geschichte", hints: ["Erzählt", "Vergangenheit", "Lernen", "Buch", "Spannend"] },
    { word: "Poesie", hints: ["Gefühle", "Wörter", "Reime", "Schön", "Schreibt"] },
    { word: "Theaterstück", hints: ["Spielt", "Bühne", "Schauspieler", "Text", "Vorstellung"] },
    { word: "Oper", hints: ["Singt", "Bühne", "Musik", "Geschichte", "Orchester"] },
    { word: "Ballett", hints: ["Tanzt", "Bühne", "Musik", "Anmutig", "Körper"] },
    { word: "Orchester", hints: ["Spielt", "Instrumente", "Musik", "Dirigent", "Konzert"] },
    { word: "Chor", hints: ["Singen", "Stimmen", "Gemeinsam", "Musik", "Gruppe"] },
    { word: "Symphonie", hints: ["Groß", "Musik", "Orchester", "Viel", "Komponist"] },
    { word: "Konzert", hints: ["Live", "Musik", "Bühne", "Publikum", "Laut"] },
    { word: "Galerie", hints: ["Kunst", "Bilder", "Zeigt", "Wand", "Betrachtet"] },
    { word: "Ausstellung", hints: ["Zeigt", "Objekte", "Kunst", "Besucht", "Lernt"] },
    { word: "Zirkus", hints: ["Zelt", "Artisten", "Tiere", "Clown", "Spannend"] },
    { word: "Festival", hints: ["Feiert", "Musik", "Draußen", "Viele", "Spaß"] },
    { word: "Karneval", hints: ["Kostüme", "Feiern", "Tanzen", "Musik", "Umzug"] },
    { word: "Halloween", hints: ["Kürbis", "Geister", "Kostüme", "Süßigkeiten", "Gruselig"] },
    { word: "Weihnachten", hints: ["Geschenke", "Christbaum", "Feiert", "Familie", "Lieder"] },
    { word: "Ostern", hints: ["Eier", "Hase", "Frühling", "Feiert", "Süßigkeiten"] },
    { word: "Geburtstag", hints: ["Kuchen", "Kerzen", "Geschenke", "Feiert", "Älter"] },
    { word: "Hochzeit", hints: ["Braut", "Bräutigam", "Ring", "Feiert", "Liebe"] },
    { word: "Beerdigung", hints: ["Trauer", "Abschied", "Blumen", "Grab", "Still"] },
    { word: "Schule", hints: ["Lernen", "Lehrer", "Klasse", "Pausenhof", "Bücher"] },
    { word: "Universität", hints: ["Studieren", "Wissen", "Vorlesung", "Campus", "Abschluss"] },
    { word: "Bibliothek", hints: ["Bücher", "Lesen", "Ausleihen", "Ruhe", "Wissen"] },
    { word: "Labor", hints: ["Forscht", "Experiment", "Wissenschaft", "Reagenzglas", "Mikroskop"] },
    { word: "Büro", hints: ["Arbeiten", "Computer", "Schreibtisch", "Kollegen", "Telefon"] },
    { word: "Fabrik", hints: ["Produziert", "Maschinen", "Arbeiter", "Herstellt", "Groß"] },
    { word: "Werkstatt", hints: ["Repariert", "Werkzeug", "Arbeitet", "Handwerk", "Schraubt"] },
    { word: "Krankenhaus", hints: ["Heilt", "Arzt", "Patient", "Medizin", "Notfall"] },
    { word: "Polizeistation", hints: ["Polizei", "Hilft", "Gesetz", "Uniform", "Wache"] },
    { word: "Feuerwache", hints: ["Feuerwehr", "Löscht", "Auto", "Schlauch", "Einsatz"] },
    { word: "Gericht", hints: ["Richter", "Urteilt", "Gesetz", "Anwalt", "Gerechtigkeit"] },
    { word: "Gefängnis", hints: ["Eingesperrt", "Strafe", "Zellen", "Wache", "Verbrechen"] },
    { word: "Kirche", hints: ["Beten", "Gottesdienst", "Glocke", "Glauben", "Heiligtum"] },
    { word: "Moschee", hints: ["Beten", "Islam", "Minarett", "Glauben", "Heiligtum"] },
    { word: "Synagoge", hints: ["Beten", "Judentum", "Thora", "Glauben", "Heiligtum"] },
    { word: "Tempel", hints: ["Beten", "Religion", "Glauben", "Heiligtum", "Alt"] },
    { word: "Friedhof", hints: ["Gräber", "Trauer", "Tot", "Ruhe", "Erde"] },
    { word: "Park", hints: ["Grün", "Bäume", "Spazieren", "Bank", "Erholung"] },
    { word: "Zoo", hints: ["Tiere", "Käfig", "Besucht", "Füttert", "Wild"] },
    { word: "Bauernhof", hints: ["Tiere", "Feld", "Ernte", "Landwirtschaft", "Traktor"] },
    { word: "Wald", hints: ["Bäume", "Dunkel", "Tiere", "Holz", "Pilze"] },
    { word: "Fluss", hints: ["Wasser", "Fließt", "Lang", "Ufer", "Fisch"] },
    { word: "Meer", hints: ["Salz", "Wasser", "Wellen", "Strand", "Fisch"] },
    { word: "See", hints: ["Wasser", "Still", "Fisch", "Boot", "Ufer"] },
    { word: "Berg", hints: ["Hoch", "Wandern", "Gipfel", "Natur", "Aussicht"] },
    { word: "Tal", hints: ["Zwischen", "Berge", "Fluss", "Grün", "Tief"] },
    { word: "Wüste", hints: ["Sand", "Trocken", "Heiß", "Kaktus", "Kamelt"] },
    { word: "Oase", hints: ["Wasser", "Wüste", "Palmen", "Grün", "Schatten"] },
    { word: "Insel", hints: ["Meer", "Umgeben", "Land", "Klein", "Strand"] },
    { word: "Höhle", hints: ["Dunkel", "Fels", "Unterirdisch", "Kalt", "Fledermäuse"] },
    { word: "Vulkan", hints: ["Feuer", "Lava", "Berg", "Rauch", "Ausbruch"] },
    { word: "Himmel", hints: ["Blau", "Wolken", "Sonne", "Sterne", "Weit"] },
    { word: "Erde", hints: ["Planet", "Boden", "Grün", "Wasser", "Lebt"] },
    { word: "Mond", hints: ["Nacht", "Himmel", "Leuchtet", "Sichel", "Satelit"] },
    { word: "Sonne", hints: ["Licht", "Warm", "Tag", "Scheint", "Rund"] },
    { word: "Stern", hints: ["Nacht", "Funkelt", "Himmel", "Klein", "Leuchtet"] },
    { word: "Wolke", hints: ["Himmel", "Regen", "Weiß", "Form", "Zieht"] },
    { word: "Blitz", hints: ["Himmel", "Licht", "Donner", "Gefährlich", "Elektrisch"] },
    { word: "Donner", hints: ["Laut", "Himmel", "Gewitter", "Grollt", "Rollend"] },
    { word: "Regen", hints: ["Nass", "Fällt", "Schirm", "Tropfen", "Pfütze"] },
    { word: "Schnee", hints: ["Kalt", "Weiß", "Fällt", "Flocke", "Winter"] },
    { word: "Wind", hints: ["Bläst", "Luft", "Sturm", "Bewegt", "Kalt"] },
    { word: "Nebel", hints: ["Dicht", "Sieht", "Schlecht", "Grau", "Feucht"] },
    { word: "Tornado", hints: ["Sturm", "Wirbel", "Zerstört", "Wind", "Trichter"] },
    { word: "Erdbeben", hints: ["Boden", "Schüttelt", "Risse", "Zerstört", "Gefährlich"] },
    { word: "Feuer", hints: ["Heiß", "Flamme", "Rauch", "Brennt", "Wärmt"] },
    { word: "Wasser", hints: ["Trinken", "Flüssig", "Nass", "Meer", "Klar"] },
    { word: "Luft", hints: ["Atmen", "Unsichtbar", "Wind", "Sauber", "Atmosphäre"] },
    { word: "Erde", hints: ["Boden", "Pflanzen", "Grün", "Garten", "Sack"] },
    { word: "Sand", hints: ["Strand", "Wüste", "Klein", "Spielt", "Burg"] },
    { word: "Stein", hints: ["Hart", "Schwer", "Fels", "Grau", "Kalt"] },
    { word: "Holz", hints: ["Baum", "Brennt", "Baut", "Möbel", "Stark"] },
    { word: "Glas", hints: ["Zerbrechlich", "Durchsichtig", "Fenster", "Flasche", "Spiegel"] },
    { word: "Metall", hints: ["Hart", "Glänzt", "Werkzeug", "Eisen", "Formbar"] },
    { word: "Plastik", hints: ["Leicht", "Formbar", "Recycelt", "Flasche", "Spielzeug"] },
    { word: "Papier", hints: ["Schreibt", "Druckt", "Blatt", "Baum", "Zeitung"] },
    { word: "Stoff", hints: ["Kleidung", "Weich", "Näht", "Faden", "Muster"] },
    { word: "Garn", hints: ["Nähen", "Stricken", "Faden", "Wolle", "Rolle"] },
    { word: "Nadel", hints: ["Näht", "Spitz", "Stich", "Faden", "Näherin"] },
    { word: "Scheren", hints: ["Schneidet", "Spitz", "Papier", "Stoff", "Klinge"] },
    { word: "Klebstoff", hints: ["Klebt", "Flüssig", "Verbindet", "Papier", "Trocknet"] },
    { word: "Band", hints: ["Bindet", "Geschenk", "Schmückt", "Stoff", "Rolle"] },
    { word: "Seil", hints: ["Bindet", "Knoten", "Stark", "Klettern", "Lang"] },
    { word: "Kette", hints: ["Metall", "Verbindet", "Hals", "Fahrrad", "Schwer"] },
    { word: "Schloss", hints: ["Sichert", "Tür", "Schlüssel", "Metall", "Öffnet"] },
    { word: "Schlüssel", hints: ["Öffnet", "Schloss", "Metall", "Tür", "Bund"] },
    { word: "Kasten", hints: ["Holz", "Lagert", "Deckel", "Verpackt", "Umliegt"] },
    { word: "Truhe", hints: ["Schatz", "Holz", "Deckel", "Alt", "Versteckt"] },
    { word: "Beutel", hints: ["Trägt", "Inhalt", "Stoff", "Einkauf", "Klein"] },
    { word: "Tasche", hints: ["Trägt", "Inhalt", "Schulter", "Hand", "Geld"] },
    { word: "Rucksack", hints: ["Trägt", "Schule", "Wandern", "Gepäck", "Rücken"] },
    { word: "Koffer", hints: ["Reisen", "Kleidung", "Packt", "Räder", "Gepäck"] },
    { word: "Schirm", hints: ["Regen", "Sonne", "Schützt", "Klappt", "Nass"] },
    { word: "Laterne", hints: ["Licht", "Dunkel", "Trägt", "Leuchtet", "Alt"] },
    { word: "Fackel", hints: ["Licht", "Feuer", "Brennbare", "Dunkel", "Hält"] },
    { word: "Kerze", hints: ["Wachs", "Flamme", "Licht", "Brennt", "Duft"] },
    { word: "Uhr", hints: ["Zeit", "Zeiger", "Tickt", "Armband", "Wecker"] },
    { word: "Kalender", hints: ["Datum", "Tage", "Monate", "Jahr", "Plan"] },
    { word: "Karte", hints: ["Orientierung", "Weg", "Reisen", "Zeigt", "Faltet"] },
    { word: "Kompass", hints: ["Richtung", "Norden", "Zeigt", "Wandern", "Magnet"] },
    { word: "Globus", hints: ["Erde", "Zeigt", "Länder", "Rund", "Dreht"] },
    { word: "Spiegel", hints: ["Reflektiert", "Bild", "Glas", "Anschauen", "Wand"] },
    { word: "Kamm", hints: ["Haare", "Kämmt", "Zinken", "Plastik", "Holz"] },
    { word: "Bürste", hints: ["Haare", "Bürstet", "Reinigt", "Borsten", "Griff"] },
    { word: "Zahnbürste", hints: ["Zähne", "Putzt", "Mund", "Hygiene", "Borsten"] },
    { word: "Seife", hints: ["Waschen", "Schaum", "Sauber", "Hände", "Duft"] },
    { word: "Handtuch", hints: ["Trocknet", "Nass", "Baumwolle", "Dusche", "Körper"] },
    { word: "Schwamm", hints: ["Reinigt", "Nass", "Saugt", "Weich", "Küche"] },
    { word: "Besen", hints: ["Fegt", "Dreck", "Boden", "Stiel", "Borsten"] },
    { word: "Eimer", hints: ["Wasser", "Trägt", "Putz", "Reinigt", "Henkel"] },
    { word: "Wischmop", hints: ["Wischt", "Boden", "Nass", "Reinigt", "Stiel"] },
    { word: "Staubsauger", hints: ["Saugt", "Dreck", "Reinigt", "Boden", "Schlauch"] },
    { word: "Föhn", hints: ["Trocknet", "Haare", "Warm", "Bläst", "Elektrisch"] },
    { word: "Rasierer", hints: ["Rasiert", "Bart", "Klinge", "Schaum", "Gesicht"] },
    { word: "Zahnpasta", hints: ["Zähne", "Putzt", "Mund", "Frisch", "Tube"] },
    { word: "Shampoo", hints: ["Haare", "Wäscht", "Schaum", "Duft", "Flasche"] },
    { word: "Seife", hints: ["Waschen", "Hände", "Schaum", "Sauber", "Duft"] },
    { word: "Creme", hints: ["Haut", "Pflegt", "Weich", "Riecht", "Tube"] },
    { word: "Parfüm", hints: ["Duft", "Sprühflasche", "Riecht", "Körper", "Besonders"] },
    { word: "Lippenstift", hints: ["Lippen", "Farbe", "Make-up", "Rund", "Dreht"] },
    { word: "Puder", hints: ["Gesicht", "Make-up", "Mattiert", "Klein", "Pinsel"] },
    { word: "Lidschatten", hints: ["Augen", "Farbe", "Make-up", "Pinsel", "Glänzt"] },
    { word: "Mascara", hints: ["Wimpern", "Schwarz", "Verlängert", "Make-up", "Bürste"] },
    { word: "Nagellack", hints: ["Nägel", "Farbe", "Glänzt", "Flasche", "Trocknet"] },
    { word: "Haarspray", hints: ["Haare", "Hält", "Fest", "Sprühflasche", "Glänzt"] },
    { word: "Kleiderbügel", hints: ["Kleidung", "Hängt", "Schrank", "Holz", "Plastik"] },
    { word: "Nähmaschine", hints: ["Näht", "Stoff", "Faden", "Motor", "Schnell"] },
    { word: "Bügeleisen", hints: ["Bügelt", "Kleidung", "Glatt", "Heiß", "Dampf"] },
    { word: "Bügelbrett", hints: ["Bügelt", "Flach", "Klappt", "Kleidung", "Beine"] },
    { word: "Wäschekorb", hints: ["Wäsche", "Sammelt", "Schmutzig", "Trägt", "Leicht"] },
    { word: "Waschpulver", hints: ["Wäscht", "Sauber", "Duft", "Pulver", "Kleidung"] },
    { word: "Weichspüler", hints: ["Wäscht", "Weich", "Duft", "Flüssig", "Kleidung"] },
    { word: "Geschirrspüler", hints: ["Reinigt", "Geschirr", "Spült", "Wasser", "Sauber"] },
    { word: "Spülmittel", hints: ["Reinigt", "Geschirr", "Schaum", "Duft", "Flasche"] },
    { word: "Reiniger", hints: ["Reinigt", "Sauber", "Flüssig", "Geruch", "Sprüh"] },
    { word: "Putztuch", hints: ["Reinigt", "Wischt", "Stoff", "Nass", "Sauber"] },
    { word: "Mülleimer", hints: ["Abfall", "Sammelt", "Deckel", "Leert", "Geruch"] },
    { word: "Müllsack", hints: ["Abfall", "Sammelt", "Plastik", "Bindet", "Geruch"] },
    { word: "Gartenhandschuhe", hints: ["Garten", "Schutz", "Hände", "Arbeit", "Dreck"] },
    { word: "Gartenschere", hints: ["Schneidet", "Pflanzen", "Blumen", "Klein", "Scharf"] },
    { word: "Hacke", hints: ["Graben", "Erde", "Garten", "Stiel", "Spitz"] },
    { word: "Rechen", hints: ["Sammelt", "Blätter", "Garten", "Zinken", "Stiel"] },
    { word: "Schubkarre", hints: ["Trägt", "Erde", "Garten", "Rad", "Schwer"] },
    { word: "Spitzhacke", hints: ["Graben", "Fels", "Hart", "Stark", "Spitz"] },
    { word: "Axt", hints: ["Holz", "Spaltet", "Scharf", "Wald", "Stiel"] },
    { word: "Säge", hints: ["Sägt", "Holz", "Scharf", "Werkzeug", "Zähne"] },
    { word: "Hammer", hints: ["Nagel", "Schlägt", "Werkzeug", "Holz", "Griff"] },
    { word: "Schraubenzieher", hints: ["Schraubt", "Dreht", "Werkzeug", "Spitze", "Griff"] },
    { word: "Zange", hints: ["Greift", "Hält", "Werkzeug", "Metall", "Draht"] },
    { word: "Maßband", hints: ["Misst", "Länge", "Meter", "Rollbar", "Zahlen"] },
    { word: "Wasserwaage", hints: ["Misst", "Gerade", "Blase", "Baut", "Horizontal"] },
    { word: "Bohrmaschine", hints: ["Bohrt", "Loch", "Wand", "Elektrisch", "Geräusch"] },
    { word: "Schleifmaschine", hints: ["Schleift", "Glatt", "Holz", "Elektrisch", "Staub"] },
    { word: "Schraubstock", hints: ["Hält", "Fest", "Werkstück", "Metall", "Zwingt"] },
    { word: "Rohrzange", hints: ["Rohre", "Greift", "Dreht", "Werkzeug", "Verstellbar"] },
    { word: "Lötkolben", hints: ["Lötet", "Verbindet", "Heiß", "Metall", "Elektronik"] },
    { word: "Schweißgerät", hints: ["Schweißt", "Metall", "Verbindet", "Funken", "Heiß"] },
    { word: "Amboss", hints: ["Schlägt", "Metall", "Schwer", "Schmied", "Werkzeug"] },
    { word: "Feile", hints: ["Feilt", "Glättet", "Metall", "Holz", "Rau"] },
    { word: "Hobel", hints: ["Hobelt", "Glättet", "Holz", "Späne", "Scharf"] },
    { word: "Meißel", hints: ["Schlägt", "Stein", "Holz", "Spitz", "Hart"] },
    { word: "Fuchsschwanz", hints: ["Sägt", "Holz", "Lang", "Hand", "Zähne"] },
    { word: "Stichsäge", hints: ["Sägt", "Formen", "Holz", "Elektrisch", "Klein"] },
    { word: "Kreissäge", hints: ["Sägt", "Gerade", "Holz", "Elektrisch", "Laut"] },
    { word: "Schleifpapier", hints: ["Schleift", "Rau", "Glättet", "Holz", "Papier"] },
    { word: "Nagelzange", hints: ["Zieht", "Nägel", "Metall", "Greift", "Klein"] },
    { word: "Seitenschneider", hints: ["Schneidet", "Draht", "Klein", "Metall", "Greift"] },
    { word: "Kombizange", hints: ["Greift", "Schneidet", "Universal", "Metall", "Zange"] },
    { word: "Winkelschleifer", hints: ["Schleift", "Trennt", "Metall", "Funken", "Laut"] },
    { word: "Akkuschrauber", hints: ["Schraubt", "Elektrisch", "Akku", "Bohrt", "Praktisch"] },
    { word: "Lötkolben", hints: ["Lötet", "Verbindet", "Heiß", "Elektronik", "Zinn"] },
    { word: "Schraubstock", hints: ["Hält", "Fixiert", "Werkstück", "Metall", "Fest"] },
    { word: "Gliedermaßstab", hints: ["Misst", "Holz", "Faltet", "Länge", "Zahlen"] },
    { word: "Bandmaß", hints: ["Misst", "Rollbar", "Länge", "Metall", "Flexibel"] },
    { word: "Zollstock", hints: ["Misst", "Holz", "Faltet", "Länge", "Zahlen"] },
    { word: "Gabelstapler", hints: ["Hebt", "Paletten", "Transport", "Lager", "Gabeln"] },
    { word: "Bagger", hints: ["Gräbt", "Erde", "Baustelle", "Schaufel", "Groß"] },
    { word: "Kran", hints: ["Hebt", "Lasten", "Hoch", "Baustelle", "Haken"] },
    { word: "Traktor", hints: ["Feld", "Zieht", "Landwirtschaft", "Große Räder", "Gerät"] },
    { word: "Mähdrescher", hints: ["Erntet", "Getreide", "Feld", "Groß", "Maschine"] },
    { word: "Pflug", hints: ["Pflügt", "Erde", "Feld", "Traktor", "Wendelt"] },
    { word: "Sämaschine", hints: ["Sät", "Samen", "Feld", "Traktor", "Reihen"] },
    { word: "Spritze", hints: ["Spritzt", "Pflanzen", "Flüssig", "Garten", "Schädlinge"] },
    { word: "Heuwender", hints: ["Wendelt", "Heu", "Feld", "Traktor", "Trocknet"] },
    { word: "Melkmaschine", hints: ["Melkt", "Kuh", "Milch", "Automatis", "Saugt"] },
    { word: "Dreschmaschine", hints: ["Drischt", "Getreide", "Trennt", "Korn", "Alt"] },
    { word: "Hackmaschine", hints: ["Hackt", "Holz", "Zerkleinert", "Garten", "Motor"] },
    { word: "Kettensäge", hints: ["Sägt", "Holz", "Motor", "Laut", "Gefährlich"] },
    { word: "Holzhacker", hints: ["Hackt", "Holz", "Klein", "Späne", "Motor"] },
    { word: "Rasenmäher", hints: ["Mäht", "Gras", "Motor", "Grün", "Rasen"] },
    { word: "Heckenschere", hints: ["Schneidet", "Hecke", "Scharf", "Elektrisch", "Garten"] },
    { word: "Blasgerät", hints: ["Bläst", "Blätter", "Luft", "Motor", "Garten"] },
    { word: "Häcksler", hints: ["Häckselt", "Pflanzen", "Klein", "Kompost", "Motor"] },
    { word: "Schneeschieber", hints: ["Schiebt", "Schnee", "Winter", "Hart", "Boden"] },
    { word: "Salzstreuer", hints: ["Streut", "Salz", "Winter", "Straße", "Rutschig"] },
    { word: "Schaufel", hints: ["Gräbt", "Schaufelt", "Erde", "Sand", "Garten"] },
    { word: "Axt", hints: ["Holz", "Spaltet", "Scharf", "Wald", "Stiel"] },
    { word: "Spitzhacke", hints: ["Gräbt", "Hart", "Stein", "Boden", "Schlägt"] },
    { word: "Harke", hints: ["Sammelt", "Blätter", "Erde", "Zinken", "Stiel"] },
    { word: "Rechen", hints: ["Sammelt", "Blätter", "Garten", "Zinken", "Stiel"] },
    { word: "Gießkanne", hints: ["Gießt", "Wasser", "Pflanzen", "Garten", "Tülle"] },
    { word: "Spaten", hints: ["Gräbt", "Umschaufelt", "Erde", "Garten", "Breit"] },
    { word: "Pflanzkelle", hints: ["Pflanzt", "Blumen", "Klein", "Garten", "Hand"] },
    { word: "Gartenschere", hints: ["Schneidet", "Blumen", "Zweige", "Scharf", "Garten"] },
    { word: "Astschere", hints: ["Schneidet", "Äste", "Groß", "Scharf", "Lang"] },
    { word: "Laubrechen", hints: ["Sammelt", "Blätter", "Leicht", "Groß", "Zinken"] },
    { word: "Gartenschlauch", hints: ["Wasser", "Bewässert", "Lang", "Rollt", "Nass"] },
    { word: "Sprenger", hints: ["Sprengt", "Wasser", "Garten", "Kreist", "Bewässert"] },
    { word: "Blumenerde", hints: ["Pflanzen", "Topf", "Erde", "Nährstoffe", "Sack"] },
    { word: "Blumentopf", hints: ["Pflanze", "Blume", "Erde", "Rund", "Keramik"] },
    { word: "Gartenmöbel", hints: ["Sitzen", "Draußen", "Tisch", "Stuhl", "Wetterfest"] },
    { word: "Sonnenschirm", hints: ["Schatten", "Sonne", "Schützt", "Klappt", "Groß"] },
    { word: "Hollywoodschaukel", hints: ["Schaukelt", "Garten", "Sitzen", "Entspannung", "Dach"] },
    { word: "Hängematte", hints: ["Liegt", "Schläft", "Zwischen", "Bäume", "Entspannung"] },
    { word: "Grill", hints: ["Fleisch", "Braten", "Feuer", "Sommer", "Rauch"] },
    { word: "Grillzange", hints: ["Dreht", "Fleisch", "Heiß", "Lang", "Grillt"] },
    { word: "Grillkohle", hints: ["Brennt", "Heiß", "Grillt", "Raucht", "Grau"] },
    { word: "Anzünder", hints: ["Zündet", "Feuer", "Schnell", "Flüssig", "Kohle"] },
    { word: "Stockbrot", hints: ["Brot", "Stock", "Lagerfeuer", "Backt", "Kind"] },
    { word: "Marshmallow", hints: ["Süß", "Röstet", "Lagerfeuer", "Weich", "Klebrig"] },
    { word: "Zelt", hints: ["Campen", "Schlafen", "Draußen", "Stoff", "Aufbau"] },
    { word: "Schlafsack", hints: ["Schläft", "Warm", "Campen", "Kuschelig", "Rollt"] },
    { word: "Isomatte", hints: ["Liegt", "Warm", "Boden", "Campen", "Weich"] },
    { word: "Campingkocher", hints: ["Kocht", "Draußen", "Gas", "Klein", "Essen"] },
    { word: "Kühlbox", hints: ["Kühlt", "Getränke", "Essen", "Picknick", "Trägt"] },
    { word: "Rucksack", hints: ["Trägt", "Wandern", "Gepäck", "Schulter", "Packt"] },
    { word: "Wanderstock", hints: ["Geht", "Stützt", "Wandern", "Holz", "Berg"] },
    { word: "Wanderkarte", hints: ["Zeigt", "Weg", "Berge", "Orientiert", "Faltet"] },
    { word: "Kompass", hints: ["Richtung", "Norden", "Zeigt", "Wandern", "Magnet"] },
    { word: "Taschenlampe", hints: ["Leuchtet", "Dunkel", "Batterie", "Trägt", "Klein"] },
    { word: "Fernglas", hints: ["Sieht", "Weit", "Groß", "Zoom", "Natur"] },
    { word: "Kamera", hints: ["Macht", "Fotos", "Bilder", "Erinnerung", "Reise"] },
    { word: "Sonnencreme", hints: ["Schützt", "Haut", "Sonne", "Creme", "Urlaub"] },
    { word: "Mückenschutz", hints: ["Schützt", "Stiche", "Sprüh", "Insekten", "Geruch"] },
    { word: "Pflaster", hints: ["Klebt", "Wunde", "Schützt", "Verletzt", "Klein"] },
    { word: "Verband", hints: ["Wunde", "Wickelt", "Schützt", "Säubert", "Medizin"] },
    { word: "Desinfektionsmittel", hints: ["Tötet", "Keime", "Reinigt", "Wunde", "Brennt"] },
    { word: "Schmerzmittel", hints: ["Nimmt", "Schmerz", "Pille", "Kopf", "Apotheke"] },
    { word: "Thermometer", hints: ["Misst", "Temperatur", "Fieber", "Glas", "Anzeige"] },
    { word: "Fieber", hints: ["Krank", "Heiß", "Kopf", "Misst", "Kalt"] },
    { word: "Husten", hints: ["Krank", "Geräusch", "Hals", "Hustensaft", "Kratzt"] },
    { word: "Schnupfen", hints: ["Nase", "Läuft", "Krank", "Niest", "Taschentuch"] },
    { word: "Erkältung", hints: ["Krank", "Nase", "Hals", "Husten", "Fieber"] },
    { word: "Grippe", hints: ["Krank", "Stark", "Fieber", "Husten", "Bett"] },
    { word: "Kopfschmerzen", hints: ["Kopf", "Schmerz", "Pille", "Pocht", "Ruhe"] },
    { word: "Bauchschmerzen", hints: ["Bauch", "Schmerz", "Essen", "Übelkeit", "Magenschmerzen"] },
    { word: "Zahnschmerzen", hints: ["Zahn", "Schmerz", "Aua", "Arzt", "Loch"] },
    { word: "Rückenschmerzen", hints: ["Rücken", "Schmerz", "Hebt", "Massiert", "Sitz"] },
    { word: "Fieberthermometer", hints: ["Misst", "Temperatur", "Fieber", "Mund", "Krank"] },
    { word: "Medikament", hints: ["Heilt", "Nimmt", "Pille", "Krank", "Apotheke"] },
    { word: "Pille", hints: ["Nimmt", "Schluckt", "Medikament", "Klein", "Heilt"] },
    { word: "Spritze", hints: ["Sticht", "Medizin", "Nadel", "Impfung", "Arzt"] },
    { word: "Verband", hints: ["Wunde", "Wickelt", "Schützt", "Gaze", "Fixiert"] },
    { word: "Pflaster", hints: ["Klebt", "Wunde", "Klein", "Schützt", "Säubert"] },
    { word: "Krücke", hints: ["Geht", "Stützt", "Bein", "Verletzt", "Hilft"] },
    { word: "Rollstuhl", hints: ["Fährt", "Sitzt", "Räder", "Bewegt", "Krank"] },
    { word: "Notarzt", hints: ["Hilft", "Notfall", "Schnell", "Krank", "Krankenwagen"] },
    { word: "Krankenwagen", hints: ["Fährt", "Schnell", "Blaulicht", "Krank", "Transportiert"] },
    { word: "Feuerwehr", hints: ["Löscht", "Feuer", "Schlauch", "Helden", "Rettet"] },
    { word: "Polizei", hints: ["Schützt", "Gesetz", "Fängt", "Ordnung", "Helfer"] },
    { word: "Sanitäter", hints: ["Hilft", "Verletzt", "Erste Hilfe", "Krankenwagen", "Schnell"] },
    { word: "Krankenschwester", hints: ["Pflegt", "Hilft", "Krankenhaus", "Medizin", "Uniform"] },
    { word: "Arzt", hints: ["Heilt", "Untersucht", "Medizin", "Patient", "Weiß"] },
    { word: "Chirurg", hints: ["Operiert", "Schneidet", "Arzt", "Krankenhaus", "Heilt"] },
    { word: "Zahnarzt", hints: ["Zähne", "Bohrt", "Schmerz", "Füllt", "Gesund"] },
    { word: "Tierarzt", hints: ["Heilt", "Tier", "Spritze", "Untersucht", "Lieb"] },
    { word: "Bauer", hints: ["Feld", "Tiere", "Erntet", "Melkt", "Land"] },
    { word: "Landwirt", hints: ["Feld", "Pflanzt", "Tiere", "Ernte", "Traktor"] },
    { word: "Gärtner", hints: ["Pflanzt", "Blumen", "Garten", "Pflegt", "Grün"] },
    { word: "Forstwirt", hints: ["Wald", "Bäume", "Pflegt", "Holz", "Fällt"] },
    { word: "Fischer", hints: ["Fängt", "Fisch", "Meer", "Angelt", "Boot"] },
    { word: "Jäger", hints: ["Jagt", "Wald", "Tier", "Waffe", "Fell"] },
    { word: "Koch", hints: ["Kocht", "Essen", "Küche", "Schmeckt", "Rezept"] },
    { word: "Bäcker", hints: ["Backt", "Brot", "Kuchen", "Ofen", "Frisch"] },
    { word: "Metzger", hints: ["Schneidet", "Fleisch", "Wurst", "Kühl", "Hackt"] },
    { word: "Kellner", hints: ["Serviert", "Essen", "Trinken", "Restaurant", "Freundlich"] },
    { word: "Gastwirt", hints: ["Besitzt", "Restaurant", "Schenkt", "Essen", "Trinken"] },
    { word: "Barmann", hints: ["Mischt", "Getränke", "Schenkt", "Bar", "Unterhält"] },
    { word: "Postbote", hints: ["Liefert", "Briefe", "Pakete", "Post", "Unterwegs"] },
    { word: "Müllmann", hints: ["Leert", "Müll", "Sammelt", "Straße", "Sauber"] },
    { word: "Bauarbeiter", hints: ["Baut", "Haus", "Maurer", "Schwer", "Baustelle"] },
    { word: "Elektriker", hints: ["Verbindet", "Strom", "Kabel", "Repariert", "Licht"] },
    { word: "Klempner", hints: ["Repariert", "Rohre", "Wasser", "Heizung", "Werkzeug"] },
    { word: "Maler", hints: ["Streicht", "Wände", "Farbe", "Pinsel", "Haus"] },
    { word: "Schreiner", hints: ["Arbeitet", "Holz", "Möbel", "Sägt", "Hobelt"] },
    { word: "Fliesenleger", hints: ["Legt", "Fliesen", "Boden", "Wand", "Bad"] },
    { word: "Dachdecker", hints: ["Deckt", "Dach", "Hoch", "Schützt", "Ziegel"] },
    { word: "Friseur", hints: ["Schneidet", "Haare", "Färbt", "Salon", "Schere"] },
    { word: "Verkäufer", hints: ["Verkauft", "Berät", "Kunde", "Geschäft", "Kasse"] },
    { word: "Kassierer", hints: ["Nimmt", "Geld", "Scannt", "Supermarkt", "Wechselt"] },
    { word: "Bürokaufmann", hints: ["Arbeitet", "Büro", "Organisiert", "Computer", "Telefon"] },
    { word: "Sekretärin", hints: ["Schreibt", "Organisiert", "Büro", "Termine", "Telefon"] },
    { word: "Manager", hints: ["Leitet", "Team", "Entscheidet", "Führt", "Verantwortlich"] },
    { word: "Geschäftsführer", hints: ["Leitet", "Firma", "Verantwortlich", "Plant", "Erfolg"] },
    { word: "Anwalt", hints: ["Recht", "Berät", "Vertritt", "Gericht", "Gesetz"] },
    { word: "Richter", hints: ["Urteilt", "Gesetz", "Gericht", "Entscheidet", "Gerecht"] },
    { word: "Polizist", hints: ["Schützt", "Fängt", "Gesetz", "Uniform", "Hilft"] },
    { word: "Feuerwehrmann", hints: ["Löscht", "Feuer", "Rettet", "Schlauch", "Uniform"] },
    { word: "Soldat", hints: ["Kämpft", "Dient", "Land", "Uniform", "Waffe"] },
    { word: "Lehrer", hints: ["Unterrichtet", "Schüler", "Wissen", "Klasse", "Tafel"] },
    { word: "Professor", hints: ["Lehrt", "Forscht", "Uni", "Wissen", "Klug"] },
    { word: "Forscher", hints: ["Entdeckt", "Experimentiert", "Wissenschaft", "Labor", "Fragt"] },
    { word: "Wissenschaftler", hints: ["Forscht", "Analysiert", "Entdeckt", "Labor", "Wissen"] },
    { word: "Ingenieur", hints: ["Baut", "Plant", "Technik", "Berechnet", "Löst"] },
    { word: "Architekt", hints: ["Plant", "Gebäude", "Zeichnet", "Haus", "Konstruiert"] },
    { word: "Designer", hints: ["Gestaltet", "Schön", "Kreativ", "Produkt", "Farben"] },
    { word: "Künstler", hints: ["Schafft", "Kunst", "Kreativ", "Malt", "Zeichnet"] },
    { word: "Musiker", hints: ["Spielt", "Singt", "Instrument", "Musik", "Konzert"] },
    { word: "Schauspieler", hints: ["Spielt", "Rolle", "Film", "Bühne", "Verkörpert"] },
    { word: "Sänger", hints: ["Singt", "Lied", "Stimme", "Bühne", "Mikrofon"] },
    { word: "Tänzer", hints: ["Tanzt", "Bewegt", "Musik", "Rhythmus", "Bühne"] },
    { word: "Sportler", hints: ["Trainiert", "Wettkampf", "Gewinnt", "Bewegt", "Fair"] },
    { word: "Trainer", hints: ["Trainiert", "Coacht", "Hilft", "Sport", "Motiviert"] },
    { word: "Journalist", hints: ["Schreibt", "Nachrichten", "Interview", "Recherchiert", "Berichtet"] },
    { word: "Fotograf", hints: ["Macht", "Fotos", "Kamera", "Bild", "Blende"] },
    { word: "Kameramann", hints: ["Filmt", "Video", "Kamera", "Bild", "Regisseur"] },
    { word: "Regisseur", hints: ["Leitet", "Film", "Theater", "Inszeniert", "Kreativ"] },
    { word: "Drehbuchautor", hints: ["Schreibt", "Film", "Geschichte", "Dialog", "Ideen"] },
    { word: "Maskenbildner", hints: ["Schminkt", "Gesicht", "Verändert", "Film", "Bühne"] },
    { word: "Kostümbildner", hints: ["Macht", "Kleidung", "Film", "Bühne", "Näht"] },
    { word: "Bühnenbildner", hints: ["Gestaltet", "Bühne", "Szenen", "Theater", "Dekoration"] },
    { word: "Requisiteur", hints: ["Sorgt", "Gegenstände", "Film", "Bühne", "Findet"] },
    { word: "Tontechniker", hints: ["Mischt", "Ton", "Musik", "Aufnimmt", "Lautstärke"] },
    { word: "Lichttechniker", hints: ["Stellt", "Licht", "Beleuchtet", "Bühne", "Effekte"] },
    { word: "Caterer", hints: ["Liefert", "Essen", "Veranstaltung", "Serviert", "Plant"] },
    { word: "DJ", hints: ["Spielt", "Musik", "Legt", "Party", "Unterhält"] },
    { word: "Barkeeper", hints: ["Mischt", "Drinks", "Bar", "Schenkt", "Unterhält"] },
    { word: "Security", hints: ["Schützt", "Kontrolliert", "Sicher", "Wacht", "Ordnung"] },
    { word: "Reinigungskraft", hints: ["Reinigt", "Sauber", "Putz", "Gebäude", "Wischen"] },
    { word: "Hausmeister", hints: ["Repariert", "Kümmert", "Gebäude", "Allrounder", "Hilft"] }
];

// DOM-Elemente abrufen
const settingsScreen = document.getElementById('settings-screen');
const gameScreen = document.getElementById('game-screen');
const gameOverScreen = document.getElementById('game-over-screen');

const numPlayersInput = document.getElementById('num-players');
const numImpostersInput = document.getElementById('num-imposters');
const startGameButton = document.getElementById('start-game-button');
const settingsErrorMessage = document.getElementById('settings-error-message');

const playerTurnMessage = document.getElementById('player-turn-message');
const gameCard = document.getElementById('game-card');
const cardRole = document.getElementById('card-role');
const cardWord = document.getElementById('card-word');
const cardHint = document.getElementById('card-hint');
const nextPlayerButton = document.getElementById('next-player-button');
const restartButton = document.getElementById('restart-button');

// Spiel-Variablen
let players = []; // Array von Objekten { type: 'word'/'imposter', value: '...' }
let currentPlayerIndex = 0;
let secretWord = '';
let imposterHint = '';
let isCardFlipped = false; // Zustand, ob die Karte gerade umgedreht ist

// Event Listener für "Spiel starten" Button
startGameButton.addEventListener('click', startGame);

// Event Listener für "Nächster Spieler" Button
nextPlayerButton.addEventListener('click', nextPlayer);

// Event Listener für die Spielkarte (zum Umdrehen)
gameCard.addEventListener('click', flipCard);

// Event Listener für "Neues Spiel starten" Button
restartButton.addEventListener('click', resetGame);

/**
 * Startet das Spiel basierend auf den Einstellungen.
 */
function startGame() {
    const numPlayers = parseInt(numPlayersInput.value);
    const numImposters = parseInt(numImpostersInput.value);

    // Validierung der Eingaben
    if (isNaN(numPlayers) || numPlayers < 2) {
        settingsErrorMessage.textContent = 'Die Anzahl der Spieler muss mindestens 2 sein.';
        return;
    }
    if (isNaN(numImposters) || numImposters < 1) {
        settingsErrorMessage.textContent = 'Die Anzahl der Imposter muss mindestens 1 sein.';
        return;
    }
    if (numImposters >= numPlayers) {
        settingsErrorMessage.textContent = 'Die Anzahl der Imposter muss kleiner sein als die Anzahl der Spieler.';
        return;
    }

    settingsErrorMessage.textContent = ''; // Fehlermeldung zurücksetzen

    // Zufälliges Wort und Hinweis auswählen
    const randomIndex = Math.floor(Math.random() * wordsAndHints.length);
    const chosenWordObject = wordsAndHints[randomIndex];
    secretWord = chosenWordObject.word;
    const randomHintIndex = Math.floor(Math.random() * chosenWordObject.hints.length);
    imposterHint = chosenWordObject.hints[randomHintIndex];

    // Spielerrollen zuweisen
    players = [];
    // Normale Spieler hinzufügen
    for (let i = 0; i < (numPlayers - numImposters); i++) {
        players.push({ type: 'word', value: secretWord });
    }
    // Imposter hinzufügen
    for (let i = 0; i < numImposters; i++) {
        players.push({ type: 'imposter', value: imposterHint });
    }

    // Spielerarray mischen, um die Rollen zufällig zu verteilen
    shuffleArray(players);

    currentPlayerIndex = 0;
    isCardFlipped = false;
    gameCard.classList.remove('flipped'); // Karte zurücksetzen, falls sie vorher geflippt war
    nextPlayerButton.textContent = 'Nächster Spieler'; // Button-Text zurücksetzen

    // Bildschirme wechseln
    settingsScreen.style.display = 'none';
    gameScreen.style.display = 'flex';
    gameOverScreen.style.display = 'none';

    updatePlayerTurnMessage();
}

/**
 * Mischt ein Array (Fisher-Yates Algorithmus).
 * @param {Array} array - Das zu mischende Array.
 */
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]]; // Elemente tauschen
    }
}

/**
 * Aktualisiert die Nachricht, welcher Spieler an der Reihe ist.
 */
function updatePlayerTurnMessage() {
    if (currentPlayerIndex < players.length) {
        playerTurnMessage.textContent = `Gib das Handy an Spieler ${currentPlayerIndex + 1} weiter.`;
    } else {
        playerTurnMessage.textContent = 'Alle haben ihre Karte gesehen.';
    }
}

/**
 * Dreht die Spielkarte um und zeigt den Inhalt an.
 */
function flipCard() {
    if (isCardFlipped) {
        // Karte ist bereits umgedreht, nichts tun
        return;
    }

    if (currentPlayerIndex >= players.length) {
        // Alle Spieler haben ihre Karten bereits gesehen, keine Aktion
        return;
    }

    const currentPlayer = players[currentPlayerIndex];

    if (currentPlayer.type === 'word') {
        cardRole.textContent = '';
        cardWord.textContent = currentPlayer.value;
        cardHint.textContent = ''; // Kein Hinweis für normale Spieler
    } else { // imposter
        cardRole.textContent = 'Imposter!';
        cardWord.textContent = ''; // Imposter hat kein Wort
        cardHint.textContent = `Hinweis: ${currentPlayer.value}`;
    }

    gameCard.classList.add('flipped'); // Fügt die Klasse hinzu, um die Karte umzudrehen
    isCardFlipped = true;
}

/**
 * Geht zum nächsten Spieler oder beendet das Spiel.
 */
function nextPlayer() {
    if (!isCardFlipped) {
        // Karte muss zuerst umgedreht werden, bevor man zum nächsten Spieler geht
        playerTurnMessage.textContent = 'Bitte drehe zuerst die Karte um!';
        return;
    }

    // Karte zurückdrehen für den nächsten Spieler
    gameCard.classList.remove('flipped');
    isCardFlipped = false;
    cardRole.textContent = ''; // Inhalte der Karte zurücksetzen
    cardWord.textContent = '';
    cardHint.textContent = '';
    playerTurnMessage.textContent = ''; // Nachricht vorübergehend leeren

    currentPlayerIndex++;

    if (currentPlayerIndex < players.length) {
        // Nächster Spieler ist an der Reihe
        updatePlayerTurnMessage();
    } else {
        // Alle Spieler haben ihre Karten gesehen, Spiel beenden
        endGame();
    }
}

/**
 * Beendet das Kartenausteilen und wechselt zum Spiel-Ende-Bildschirm.
 */
function endGame() {
    gameScreen.style.display = 'none';
    gameOverScreen.style.display = 'flex';
    gameOverScreen.style.flexDirection = 'column';
    gameOverScreen.style.alignItems = 'center';
}

/**
 * Setzt das Spiel auf den Anfangszustand zurück.
 */
function resetGame() {
    settingsScreen.style.display = 'flex';
    settingsScreen.style.flexDirection = 'column';
    settingsScreen.style.alignItems = 'center';
    gameScreen.style.display = 'none';
    gameOverScreen.style.display = 'none';

    // Zurücksetzen der Spielvariablen
    players = [];
    currentPlayerIndex = 0;
    secretWord = '';
    imposterHint = '';
    isCardFlipped = false;
    gameCard.classList.remove('flipped'); // Sicherstellen, dass die Karte nicht geflippt ist
    settingsErrorMessage.textContent = ''; // Fehlermeldung zurücksetzen
    playerTurnMessage.textContent = ''; // Nachricht zurücksetzen
}

// Initialisierung beim Laden der Seite: Zeigt den Einstellungsbildschirm an
resetGame();